<?php

// SPDX-License-Identifier: GPL-3.0-or-later

declare(strict_types=1);

namespace Reporion\Tests\Plugin;

use DateTimeImmutable;
use Reporion\Auth\FlatFileUserStore;
use Reporion\Auth\Grant;
use Reporion\Auth\GrantRole;
use Reporion\Http\Request;
use Reporion\Http\Response;
use Reporion\Http\Session;
use Reporion\Index\Sqlite;
use Reporion\Kernel;
use Reporion\Plugin\Dicom\Pacs;
use Reporion\Plugin\Dicom\Plugin;
use Reporion\Plugin\Dicom\Study;
use Reporion\Plugin\Loader;
use Reporion\Service\InstanceSettings;
use Reporion\Storage\FlatFile;
use Reporion\Tests\Http\HttpTestCase;
use Reporion\Tests\Support\CnpTest;
use Symfony\Component\Yaml\Yaml;

/**
 * plugins/dicom against a fake findscu: the runner writes dcmtk-shaped
 * answer files (ISO-8859-1, as a PACS in ISO_IR 100 answers) for the
 * studies matching the query keys. Every name, CNP and UID is made up; the
 * CNPs are generated by the checksum rule (invariant 10).
 */
final class DicomTest extends HttpTestCase
{
    private const REPORT = 'reports:ct:mioveni:260928-ionescu-maria';
    private const UID1 = '1.2.826.0.1.3680043.2.1125.1.1';
    private const UID2 = '1.2.826.0.1.3680043.2.1125.2.1';
    private const UID3 = '1.2.826.0.1.3680043.2.1125.3.1';

    private string $cnp;

    /** @var list<list<string>> every command line run */
    private array $calls = [];

    /** @var array<string, list<array<string, string>>> host → its studies */
    private array $pacs = [];

    /** @var array<string, array{0: int, 1: string}> host → a failure to answer with */
    private array $fail = [];

    protected function setUp(): void
    {
        parent::setUp();
        Loader::registerAutoload(\dirname(__DIR__, 2) . '/plugins', 'dicom');
        $this->cnp = CnpTest::make(2, '800115');
        $this->config['sites'] = [
            'mioveni' => ['name' => 'Spital Test', 'accession_code' => 'MV', 'devices' => []],
            'scuc' => ['name' => 'Alt Spital', 'devices' => []],
            'nopacs' => ['name' => 'Fara PACS', 'devices' => []],
        ];
        $this->config['plugins'] = [
            'enabled' => ['dicom'],
            'settings' => ['dicom' => [
                'findscu' => '/opt/dcmtk/bin/findscu',
                'servers' => [
                    'mioveni' => ['host' => '10.0.0.5', 'port' => 104, 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI'],
                    'scuc' => ['host' => '10.0.1.5', 'port' => 11112, 'aet' => 'SCPACS', 'calling_aet' => 'RP_SCUC'],
                    'nopacs' => ['host' => '10.0.2.5', 'port' => 104, 'aet' => 'NOPACS', 'calling_aet' => ''],
                ],
            ]],
        ];
        $users = new FlatFileUserStore($this->dataRoot);
        $users->create('owner', password_hash('x', PASSWORD_ARGON2ID), true);
        $users->create('viewer', password_hash('x', PASSWORD_ARGON2ID), false, [new Grant('reports', GrantRole::Viewer)]);
        Plugin::$today = new DateTimeImmutable('2026-09-29');
        Plugin::$runner = $this->fakeFindscu(...);

        $this->pacs['10.0.0.5'] = [
            self::study(self::UID1, '20260928', '101500', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT TORACE NATIV', 'MV26001', 'POPESCU^ION'),
            self::study(self::UID2, '20260928', '113000', 'MR', "POP\xC9SCU^ANA", 'PACS00042', 'IRM CEREBRAL', 'MV26002', ''),
            self::study(self::UID3, '20260928', '090000', 'CT', 'DUMITRU^ELENA', CnpTest::make(2, '750310'), 'CT ABDOMEN', 'MV26003', ''),
        ];
        $this->pacs['10.0.1.5'] = [];
    }

    protected function tearDown(): void
    {
        Plugin::$runner = null;
        Plugin::$today = null;
        parent::tearDown();
    }

    public function testTheWorklistQueriesEachPacsPerModalityAndMarksReportedStudies(): void
    {
        $this->fail['10.0.1.5'] = [2, "E: Association Request Failed: 0006:031c TCP Initialization Error: Connection refused\n"];
        $this->storage()->create('reports:ct:mioveni:260928-dumitru-elena', ['title' => 'DUMITRU Elena', 'visibility' => 'private', 'study_uid' => self::UID3], "# DUMITRU Elena\n", 'owner');

        $page = $this->get('owner', '/x/dicom/worklist');

        self::assertSame(200, $page->status);
        self::assertCount(3, $this->calls, 'a site with a PACS × 2 modalities, the failing one asked once; the site without our AE title for it never');
        $first = $this->calls[0];
        self::assertSame('/opt/dcmtk/bin/findscu', $first[0]);
        self::assertSame(['-aet', 'RP_MIOVENI'], \array_slice($first, 2, 2), "the site's own calling AE title");
        self::assertSame(['-aet', 'RP_SCUC'], \array_slice($this->calls[2], 2, 2), 'and the other site its own');
        self::assertSame(['-aec', 'MVPACS'], \array_slice($first, 4, 2));
        self::assertSame(['10.0.0.5', '104'], \array_slice($first, -2));
        self::assertContains('StudyDate=20260926-20260929', $first, '3 days back from today');
        self::assertContains('ModalitiesInStudy=CT', $first);
        foreach ($this->calls as $argv) {
            self::assertStringNotContainsString('IONESCU', implode(' ', $argv), 'no name ever on a command line');
            self::assertStringNotContainsString($this->cnp, implode(' ', $argv));
        }
        self::assertStringContainsString('IONESCU Maria', $page->body);
        self::assertStringContainsString('POPÉSCU Ana', $page->body, 'ISO-8859-1 read as UTF-8');
        self::assertStringContainsString('no CNP', $page->body, 'a PACS id that is not a CNP is flagged');
        self::assertStringContainsString('/new?prefill=dicom&amp;ref=' . rawurlencode('mioveni:CT:' . self::UID1), $page->body);
        self::assertStringContainsString('href="/reports:ct:mioveni:260928-dumitru-elena"', $page->body, 'already reported: a link');
        self::assertStringContainsString('The PACS did not answer', $page->body, 'the other site still listed its own error');
        self::assertLessThan(strpos($page->body, 'CT ABDOMEN'), strpos($page->body, 'IRM CEREBRAL'), 'newest first');

        $this->calls = [];
        $one = $this->get('owner', '/x/dicom/worklist?site=mioveni&from=2026-09-28&to=2026-09-28');
        self::assertCount(2, $this->calls);
        self::assertContains('StudyDate=20260928', $this->calls[0]);
        self::assertStringContainsString('IONESCU Maria', $one->body);

        self::assertStringContainsString('at most 31 days', $this->get('owner', '/x/dicom/worklist?from=2026-01-01&to=2026-09-28')->body);
        self::assertSame(404, $this->get('viewer', '/x/dicom/worklist')->status);
    }

    public function testStartingAReportFillsTheGuidedFormFromTheStudy(): void
    {
        $form = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:CT:' . self::UID1));

        self::assertSame(200, $form->status);
        self::assertContains('StudyInstanceUID=' . self::UID1, $this->calls[0], 'the one study, by UID');
        foreach (['value="IONESCU Maria"', 'value="' . $this->cnp . '"', 'value="2026-09-28"', 'value="10:15"', 'value="Ct Torace Nativ"', 'POPESCU Ion',
            'name="study_uid" value="' . self::UID1 . '"', 'name="pacs_accession" value="MV26001"'] as $needle) {
            self::assertStringContainsString($needle, $form->body);
        }

        $created = $this->post('owner', '/new', [
            'guided' => '1', 'action' => 'create', 'name' => 'IONESCU Maria', 'cnp' => $this->cnp, 'date' => '2026-09-28', 'time' => '10:15',
            'modality' => 'CT', 'site' => 'mioveni', 'regions' => ['chest'], 'title' => 'Ct Torace Nativ',
            'study_uid' => self::UID1, 'pacs_accession' => 'MV26001',
        ]);
        self::assertSame(302, $created->status);
        $fm = $this->storage()->read(self::REPORT)->frontmatter;
        self::assertSame(self::UID1, $fm['study_uid']);
        self::assertSame('MV26001', $fm['pacs_accession']);
        self::assertStringStartsWith('MV-CT-26-', (string) $fm['accession'], "Reporion's own accession stays (D20)");

        $noCnp = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:MR:' . self::UID2));
        self::assertStringContainsString('value="POPÉSCU Ana"', $noCnp->body);
        self::assertStringNotContainsString('PACS00042', $noCnp->body, 'not a CNP: never put in the CNP field');

        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:CT:9.9.9'))->status, 'not in the PACS');
        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('nopacs:CT:' . self::UID1))->status, 'a site without a PACS');
        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=mioveni:CT:1.2;rm')->status);
    }

    public function testThePacsTabLinksTheStudyAndFillsOnlyWhatTheReportLacks(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria'], 'referrer' => 'Dr. Deja',
        ], "# IONESCU Maria\n\n## CT torace\n", 'owner');

        $tab = $this->get('owner', '/x/dicom/study/' . $page->pid);
        self::assertSame(200, $tab->status);
        self::assertContains('StudyDate=20260928', $this->calls[0]);
        self::assertContains('ModalitiesInStudy=CT', $this->calls[0], "the report's own modality");
        self::assertCount(1, $this->calls);
        self::assertStringContainsString('same name', $tab->body);
        self::assertLessThan(strpos($tab->body, 'DUMITRU'), strpos($tab->body, 'IONESCU Maria'), 'the likeliest first');
        self::assertStringNotContainsString('IRM CEREBRAL', $tab->body, 'another modality');

        $done = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1, 'day' => '2026-09-28']);
        self::assertSame(302, $done->status);
        self::assertStringContainsString('done=1', $done->headers['Location']);
        self::assertStringNotContainsString('ionescu', strtolower($done->headers['Location']));

        $updated = $this->storage()->read(self::REPORT);
        self::assertSame(2, $updated->rev);
        $fm = $updated->frontmatter;
        self::assertSame(['name' => 'Ionescu Maria', 'cnp' => $this->cnp, 'sex' => 'F', 'born' => 1980], $fm['patient'], 'blanks filled, the name kept as written');
        self::assertSame('Dr. Deja', $fm['referrer'], 'never overwritten');
        self::assertStringStartsWith('2026-09-28T10:15:00', (string) $fm['study_date'], 'the time added to the same day');
        self::assertSame('Ct Torace Nativ', $fm['exam_title']);
        self::assertSame(self::UID1, $fm['study_uid']);
        self::assertSame('MV26001', $fm['pacs_accession']);
        self::assertSame($page->body, $updated->body);

        self::assertStringContainsString('done=0', $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1])->headers['Location']);
        self::assertSame(2, $this->storage()->read(self::REPORT)->rev, 'nothing new: no revision');
        self::assertStringContainsString('>linked<', $this->get('owner', '/x/dicom/study/' . $page->pid)->body);

        $other = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID3]);
        self::assertSame(422, $other->status);
        self::assertStringContainsString('The CNP in the PACS is not the one on this report', $other->body, 'the CNP check comes first');

        $audit = (string) file_get_contents((string) glob($this->dataRoot . '/audit/*.ndjson')[0]);
        self::assertStringContainsString('"via":"dicom"', $audit);
        self::assertStringNotContainsString('ionescu', strtolower($audit), 'no path or name in the audit (invariant 8)');
    }

    public function testAReportLinkedToAnotherStudyIsNotRelinked(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'study_date' => '2026-09-28', 'study_uid' => '1.2.3',
        ], "# IONESCU Maria\n", 'owner');

        $refused = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1]);

        self::assertSame(422, $refused->status);
        self::assertStringContainsString('already linked to another study', $refused->body);
        self::assertSame(1, $this->storage()->read(self::REPORT)->rev);
    }

    public function testThePacsTabNeedsWriteAccessAndAReport(): void
    {
        $page = $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private'], "# IONESCU Maria\n", 'owner');
        $note = $this->storage()->create('docs:note', ['title' => 'Note', 'visibility' => 'private'], "Text\n", 'owner');

        self::assertSame(404, $this->get('viewer', '/x/dicom/study/' . $page->pid)->status);
        self::assertSame(404, $this->get('owner', '/x/dicom/study/' . $note->pid)->status);
        self::assertSame([], $this->calls, 'the PACS is not asked on a refusal');
        self::assertStringContainsString('/x/dicom/study/' . $page->pid, $this->get('owner', '/' . self::REPORT)->body, 'the PACS tab on the report');
    }

    public function testTheEchoScreenIsTheOwnersAndUsesEchoscuNextToFindscu(): void
    {
        $this->fail['10.0.1.5'] = [1, "E: Association Rejected:\nE: Reason: Called AE Title Not Recognized\n"];

        $page = $this->get('owner', '/x/dicom/echo');

        self::assertSame(200, $page->status);
        self::assertSame('/opt/dcmtk/bin/echoscu', $this->calls[0][0]);
        self::assertSame(['-aet', 'RP_MIOVENI', '-aec', 'MVPACS'], \array_slice($this->calls[0], 1, 4));
        self::assertStringContainsString('RP_SCUC → SCPACS', $page->body);
        self::assertStringContainsString('answers', $page->body);
        self::assertStringContainsString('The PACS refused us', $page->body);
        self::assertSame(404, $this->get('viewer', '/x/dicom/echo')->status);
    }

    public function testTheOwnerSetsThePacsOfEachSiteInAdmin(): void
    {
        $admin = $this->get('owner', '/admin/plugins');
        self::assertStringContainsString('name="servers[mioveni][host]"', $admin->body, 'one row per configured site');
        self::assertStringContainsString('name="servers[nopacs][aet]"', $admin->body);
        self::assertStringContainsString('name="servers[scuc][calling_aet]"', $admin->body, 'our AE title, per site');
        self::assertStringNotContainsString('name="calling_aet"', $admin->body, 'no longer one for all sites');

        $saved = $this->post('owner', '/admin/plugins/dicom/settings', [
            'findscu' => '/usr/local/bin/findscu', 'timeout' => '15', 'modalities' => 'CT, MR', 'lookback_days' => '2',
            'servers' => [
                'mioveni' => ['host' => '192.168.3.50', 'port' => '104', 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI'],
                'scuc' => ['host' => '', 'port' => '', 'aet' => '', 'calling_aet' => ''],
                'gone' => ['host' => '10.9.9.9', 'port' => '104', 'aet' => 'X', 'calling_aet' => 'Y'],
            ],
        ]);
        self::assertSame(302, $saved->status);
        $stored = Yaml::parseFile($this->dataRoot . '/' . InstanceSettings::FILE)['plugins']['settings']['dicom'];
        self::assertSame(['mioveni' => ['host' => '192.168.3.50', 'port' => 104, 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI'], 'scuc' => ['host' => '', 'port' => 104, 'aet' => '', 'calling_aet' => '']], $stored['servers'], 'a site not configured is dropped');
        self::assertSame('/usr/local/bin/findscu', $stored['findscu']);

        $bad = ['findscu' => '/usr/bin/findscu', 'timeout' => '15', 'modalities' => 'CT', 'lookback_days' => '2'];
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h', 'port' => '104', 'aet' => 'A', 'calling_aet' => 'TOO LONG AE TITLE XX']]])->status);
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h; rm', 'port' => '104', 'aet' => 'A']]])->status);
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', ['findscu' => 'findscu'] + $bad)->status, 'a full path');
    }

    public function testNamesAndDatesAreReadTheReporionWay(): void
    {
        self::assertSame('IONESCU Maria Elena', Study::name('ionescu^MARIA^ELENA'));
        self::assertSame('POPA Ion', Study::name('POPA^ION=ポパ^イオン'));
        self::assertSame(['XR'], Study::modalities(['ModalitiesInStudy' => 'CR\\DX\\SR']));
        self::assertSame(['CT'], Study::modalities([], 'CT'), 'not returned: the one queried');
        self::assertSame('2026-09-28 07:05', Study::when(['StudyDate' => '20260928', 'StudyTime' => '070512.123'])?->format('Y-m-d H:i'));
        self::assertTrue(Pacs::sameName('IONESCU Maria', 'Ionescu MARIA'));
        self::assertTrue(Pacs::sameName('POPESCU Ana', 'POPÉSCU Ana'), 'diacritics aside');
        self::assertFalse(Pacs::sameName('IONESCU Maria', 'IONESCU Mara'));
    }

    // The fake findscu/echoscu

    /**
     * @param list<string> $argv
     *
     * @return array{0: int, 1: string}
     */
    private function fakeFindscu(array $argv, int $timeout): array
    {
        $this->calls[] = $argv;
        $host = $argv[\count($argv) - 2];
        if (isset($this->fail[$host])) {
            return $this->fail[$host];
        }
        if (str_ends_with($argv[0], 'echoscu')) {
            return [0, ''];
        }
        $keys = [];
        $dir = '';
        foreach ($argv as $i => $arg) {
            if ($arg === '-k' && str_contains($argv[$i + 1], '=')) {
                [$k, $v] = explode('=', $argv[$i + 1], 2);
                $keys[$k] = $v;
            }
            if ($arg === '-od') {
                $dir = $argv[$i + 1];
            }
        }
        $n = 0;
        foreach ($this->pacs[$host] ?? [] as $study) {
            if (isset($keys['StudyInstanceUID']) && $keys['StudyInstanceUID'] !== $study['StudyInstanceUID']) {
                continue;
            }
            if (isset($keys['ModalitiesInStudy']) && $keys['ModalitiesInStudy'] !== $study['ModalitiesInStudy']) {
                continue;
            }
            if (isset($keys['StudyDate'])) {
                [$from, $to] = array_pad(explode('-', $keys['StudyDate']), 2, null);
                $to ??= $from;
                if ($study['StudyDate'] < $from || $study['StudyDate'] > $to) {
                    continue;
                }
            }
            $xml = '<?xml version="1.0" encoding="ISO-8859-1"?>' . "\n" . '<data-set xfer="1.2.840.10008.1.2.1" name="Little Endian Explicit">' . "\n";
            foreach ($study as $name => $value) {
                $xml .= '<element tag="0000,0000" vr="LO" vm="1" len="' . \strlen($value) . '" name="' . $name . '">' . htmlspecialchars($value, ENT_XML1, 'ISO-8859-1') . "</element>\n";
            }
            file_put_contents(\sprintf('%s/rsp%04d.xml', $dir, ++$n), $xml . "</data-set>\n");
        }

        return [0, ''];
    }

    /** @return array<string, string> one study, as the PACS stores it (ISO-8859-1 bytes) */
    private static function study(string $uid, string $date, string $time, string $modality, string $name, string $id, string $description, string $accession, string $referrer): array
    {
        return [
            'SpecificCharacterSet' => 'ISO_IR 100', 'StudyDate' => $date, 'StudyTime' => $time, 'AccessionNumber' => $accession,
            'ReferringPhysicianName' => $referrer, 'StudyDescription' => $description, 'PatientName' => $name, 'PatientID' => $id,
            'PatientBirthDate' => '19800115', 'PatientSex' => 'F', 'StudyInstanceUID' => $uid, 'ModalitiesInStudy' => $modality,
        ];
    }

    /** @param array<string, mixed> $fields */
    private function post(string $user, string $path, array $fields): Response
    {
        return Kernel::boot($this->config)->handle(new Request('POST', $path, cookies: ['reporion' => $this->cookie($user)], body: http_build_query($fields)));
    }

    private function get(string $user, string $path): Response
    {
        [$route, $query] = array_pad(explode('?', $path, 2), 2, '');
        parse_str($query, $params);

        return Kernel::boot($this->config)->handle(new Request('GET', $route, query: array_map('strval', $params), cookies: ['reporion' => $this->cookie($user)]));
    }

    private function cookie(string $user): string
    {
        return (new Session('test-secret', 'reporion', 3600, new FlatFileUserStore($this->dataRoot)))->issue($user);
    }

    private function storage(): FlatFile
    {
        return new FlatFile($this->dataRoot, new Sqlite((string) $this->config['paths']['index'], \dirname(__DIR__, 2) . '/migrations'));
    }
}
