<?php

// SPDX-License-Identifier: GPL-3.0-or-later

declare(strict_types=1);

namespace Reporion\Tests\Plugin;

use DateTimeImmutable;
use Reporion\Auth\FlatFileUserStore;
use Reporion\Auth\Grant;
use Reporion\Auth\GrantRole;
use Reporion\Cli\Output;
use Reporion\Cli\PluginTaskCommand;
use Reporion\Http\Request;
use Reporion\Http\Response;
use Reporion\Http\Session;
use Reporion\Index\Sqlite;
use Reporion\Audit\AuditLog;
use Reporion\Kernel;
use Reporion\Plugin\Hooks;
use Reporion\Schema\Loader as SchemaLoader;
use Reporion\Service\Accessions;
use Reporion\Service\Maintenance\MaintenanceRunner;
use Reporion\Service\Render;
use Reporion\Support\AccessionFormat;
use Reporion\Plugin\Dicom\Pacs;
use Reporion\Plugin\Dicom\Plugin;
use Reporion\Plugin\Dicom\Study;
use Reporion\Plugin\Loader;
use Reporion\Service\InstanceSettings;
use Reporion\Storage\FlatFile;
use Reporion\Support\Exams;
use Reporion\Tests\Http\HttpTestCase;
use Reporion\Tests\Support\CnpTest;
use Symfony\Component\Yaml\Yaml;

/**
 * plugins/dicom against a fake findscu: the runner writes dcmtk-shaped
 * answer files (ISO-8859-1, as a PACS in ISO_IR 100 answers) for the
 * studies matching the query keys. Every name, CNP and UID is made up; the
 * CNPs are generated by the checksum rule (invariant 10).
 */
final class DicomTest extends HttpTestCase
{
    private const REPORT = 'reports:ct:mioveni:260928-ionescu-maria';
    private const UID1 = '1.2.826.0.1.3680043.2.1125.1.1';
    private const UID2 = '1.2.826.0.1.3680043.2.1125.2.1';
    private const UID3 = '1.2.826.0.1.3680043.2.1125.3.1';

    private string $cnp;

    /** @var list<list<string>> every command line run */
    private array $calls = [];

    /** @var list<array<string, string>> the patient keys of every query file findscu was handed */
    private array $queryFiles = [];

    /** @var array<string, list<array<string, string>>> host → its studies */
    private array $pacs = [];

    /** @var array<string, array{0: int, 1: string}> host → a failure to answer with */
    private array $fail = [];

    protected function setUp(): void
    {
        parent::setUp();
        Loader::registerAutoload(\dirname(__DIR__, 2) . '/plugins', 'dicom');
        $this->cnp = CnpTest::make(2, '800115');
        $this->config['sites'] = [
            'mioveni' => ['name' => 'Spital Test', 'accession_code' => 'MV', 'devices' => []],
            'scuc' => ['name' => 'Alt Spital', 'devices' => []],
            'nopacs' => ['name' => 'Fara PACS', 'devices' => []],
        ];
        $this->config['plugins'] = [
            'enabled' => ['dicom'],
            'settings' => ['dicom' => [
                'findscu' => '/opt/dcmtk/bin/findscu',
                'servers' => [
                    'mioveni' => ['host' => '10.0.0.5', 'port' => 104, 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI'],
                    'scuc' => ['host' => '10.0.1.5', 'port' => 11112, 'aet' => 'SCPACS', 'calling_aet' => 'RP_SCUC'],
                    'nopacs' => ['host' => '10.0.2.5', 'port' => 104, 'aet' => 'NOPACS', 'calling_aet' => ''],
                ],
            ]],
        ];
        $users = new FlatFileUserStore($this->dataRoot);
        $users->create('owner', password_hash('x', PASSWORD_ARGON2ID), true);
        $users->create('viewer', password_hash('x', PASSWORD_ARGON2ID), false, [new Grant('reports', GrantRole::Viewer)]);
        Plugin::$today = new DateTimeImmutable('2026-09-29');
        Plugin::$runner = $this->fakeFindscu(...);

        $this->pacs['10.0.0.5'] = [
            self::study(self::UID1, '20260928', '101500', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT TORACE NATIV', 'MV26001', 'POPESCU^ION'),
            self::study(self::UID2, '20260928', '113000', 'MR', "POP\xC9SCU^ANA", 'PACS00042', 'IRM CEREBRAL', 'MV26002', ''),
            self::study(self::UID3, '20260928', '090000', 'CT', 'DUMITRU^ELENA', CnpTest::make(2, '750310'), 'CT ABDOMEN', 'MV26003', ''),
        ];
        $this->pacs['10.0.1.5'] = [];
    }

    protected function tearDown(): void
    {
        Plugin::$runner = null;
        Plugin::$today = null;
        parent::tearDown();
    }

    public function testTheWorklistCanBeLimitedToAPatientByNameSentInAQueryFile(): void
    {
        $page = $this->post('owner', '/x/dicom/worklist', ['site' => 'mioveni', 'modality' => 'CT', 'patient' => 'Ionesc', 'from' => '2026-09-26', 'to' => '2026-09-29']);

        self::assertSame(200, $page->status);
        self::assertStringContainsString('IONESCU', $page->body);
        self::assertStringNotContainsString('DUMITRU', $page->body, 'only the patient asked for');
        self::assertContains(['PatientName' => 'IONESC*'], $this->queryFiles, 'the name went in the query file');
        self::assertStringNotContainsString('IONESC', implode(' ', array_merge(...$this->calls)), 'never on the command line');
        self::assertStringContainsString('name="patient" value="Ionesc"', $page->body, 'the form keeps it');

        $this->calls = [];
        $this->queryFiles = [];
        $all = $this->post('owner', '/x/dicom/worklist', ['site' => 'mioveni', 'modality' => 'CT', 'patient' => '', 'from' => '2026-09-26', 'to' => '2026-09-29']);
        self::assertStringContainsString('DUMITRU', $all->body, 'an empty name lists everyone');
        self::assertSame([], $this->queryFiles);

        $get = $this->get('owner', '/x/dicom/worklist?site=mioveni&modality=CT&patient=Ionescu&from=2026-09-26&to=2026-09-29');
        self::assertStringContainsString('DUMITRU', $get->body, 'a name in a URL is ignored (D1)');
    }

    public function testTheWorklistsPatientFieldTakesACnpAsPatientId(): void
    {
        // All digits (spaces aside) is a CNP: asked as PatientID, rows kept on an exact match
        $spaced = trim(chunk_split($this->cnp, 4, ' '));
        $page = $this->post('owner', '/x/dicom/worklist', ['site' => 'mioveni', 'modality' => 'CT', 'patient' => $spaced, 'from' => '2026-09-26', 'to' => '2026-09-29']);

        self::assertSame(200, $page->status);
        self::assertSame([['PatientID' => $this->cnp]], $this->queryFiles, 'the CNP went in the query file, as PatientID, spaces dropped');
        self::assertStringContainsString('IONESCU', $page->body);
        self::assertStringNotContainsString('DUMITRU', $page->body, 'only the patient with that CNP');
        self::assertStringNotContainsString($this->cnp, implode(' ', array_merge(...$this->calls)), 'never on the command line');

        $get = $this->get('owner', '/x/dicom/worklist?site=mioveni&modality=CT&patient=' . $this->cnp . '&from=2026-09-26&to=2026-09-29');
        self::assertStringContainsString('DUMITRU', $get->body, 'a CNP in a URL is ignored (D1)');
    }

    public function testTheWorklistQueriesEachPacsPerModalityAndMarksReportedStudies(): void
    {
        $this->fail['10.0.1.5'] = [2, "E: Association Request Failed: 0006:031c TCP Initialization Error: Connection refused\n"];
        $this->storage()->create('reports:ct:mioveni:260928-dumitru-elena', ['title' => 'DUMITRU Elena', 'visibility' => 'private', 'study_uid' => self::UID3], "# DUMITRU Elena\n", 'owner');

        $idle = $this->get('owner', '/x/dicom/worklist');
        self::assertSame(200, $idle->status);
        self::assertSame([], $this->calls, 'opening the page asks no PACS; the Query button does');
        self::assertStringContainsString('then Query', $idle->body);
        self::assertStringContainsString('name="from" value="2026-09-26"', $idle->body, 'the default range, ready to submit');

        $page = $this->get('owner', '/x/dicom/worklist?site=&from=2026-09-26&to=2026-09-29');

        self::assertSame(200, $page->status);
        self::assertCount(3, $this->calls, 'a site with a PACS × 2 modalities, the failing one asked once; the site without our AE title for it never');
        $first = $this->calls[0];
        self::assertSame('/opt/dcmtk/bin/findscu', $first[0]);
        self::assertSame(['-aet', 'RP_MIOVENI'], \array_slice($first, 2, 2), "the site's own calling AE title");
        self::assertSame(['-aet', 'RP_SCUC'], \array_slice($this->calls[2], 2, 2), 'and the other site its own');
        self::assertSame(['-aec', 'MVPACS'], \array_slice($first, 4, 2));
        self::assertSame(['10.0.0.5', '104'], \array_slice($first, -2));
        self::assertContains('StudyDate=20260926-20260929', $first, '3 days back from today');
        self::assertContains('ModalitiesInStudy=CT', $first);
        foreach ($this->calls as $argv) {
            self::assertStringNotContainsString('IONESCU', implode(' ', $argv), 'no name ever on a command line');
            self::assertStringNotContainsString($this->cnp, implode(' ', $argv));
        }
        self::assertStringContainsString('IONESCU Maria', $page->body);
        self::assertStringContainsString('POPÉSCU Ana', $page->body, 'ISO-8859-1 read as UTF-8');
        self::assertStringContainsString('no CNP', $page->body, 'a PACS id that is not a CNP is flagged');
        self::assertStringContainsString('/new?prefill=dicom&amp;ref=' . rawurlencode('mioveni:CT:' . self::UID1), $page->body);
        self::assertStringContainsString('href="/reports:ct:mioveni:260928-dumitru-elena"', $page->body, 'already reported: a link');
        self::assertStringContainsString('The PACS did not answer', $page->body, 'the other site still listed its own error');
        self::assertLessThan(strpos($page->body, 'CT ABDOMEN'), strpos($page->body, 'IRM CEREBRAL'), 'newest first');

        $this->calls = [];
        $one = $this->get('owner', '/x/dicom/worklist?site=mioveni&from=2026-09-28&to=2026-09-28');
        self::assertCount(2, $this->calls);
        self::assertContains('StudyDate=20260928', $this->calls[0]);
        self::assertStringContainsString('IONESCU Maria', $one->body);
        self::assertStringContainsString('<option value="">All (CT, MR)</option>', $one->body, 'the modalities from the settings');

        $this->calls = [];
        $mr = $this->get('owner', '/x/dicom/worklist?site=mioveni&modality=MR&from=2026-09-28&to=2026-09-28');
        self::assertCount(1, $this->calls, 'one modality, one query');
        self::assertContains('ModalitiesInStudy=MR', $this->calls[0]);
        self::assertStringContainsString('<option value="MR" selected>', $mr->body);

        $this->calls = [];
        $this->get('owner', '/x/dicom/worklist?site=mioveni&modality=XA&from=2026-09-28&to=2026-09-28');
        self::assertCount(2, $this->calls, 'a modality not in the settings is ignored: all of them');

        self::assertStringContainsString('at most 31 days', $this->get('owner', '/x/dicom/worklist?from=2026-01-01&to=2026-09-28')->body);
        self::assertSame(404, $this->get('viewer', '/x/dicom/worklist')->status);
    }

    public function testStartingAReportFillsTheGuidedFormFromTheStudy(): void
    {
        $form = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:CT:' . self::UID1));

        self::assertSame(200, $form->status);
        self::assertContains('StudyInstanceUID=' . self::UID1, $this->calls[0], 'the one study, by UID');
        foreach (['value="IONESCU Maria"', 'value="' . $this->cnp . '"', 'value="2026-09-28"', 'value="10:15"', 'value="Ct Torace Nativ"', 'POPESCU Ion',
            'name="study_uid" value="' . self::UID1 . '"', 'name="pacs_accession" value="MV26001"'] as $needle) {
            self::assertStringContainsString($needle, $form->body);
        }

        $created = $this->post('owner', '/new', [
            'guided' => '1', 'action' => 'create', 'name' => 'IONESCU Maria', 'cnp' => $this->cnp, 'date' => '2026-09-28', 'time' => '10:15',
            'modality' => 'CT', 'site' => 'mioveni', 'regions' => ['chest'], 'title' => 'Ct Torace Nativ',
            'study_uid' => self::UID1, 'pacs_accession' => 'MV26001',
        ]);
        self::assertSame(302, $created->status);
        $fm = $this->storage()->read(self::REPORT)->frontmatter;
        self::assertSame(self::UID1, $fm['exams'][0]['study_uid']);
        self::assertSame('MV26001', $fm['exams'][0]['pacs_accession']);
        self::assertStringStartsWith('MV-CT-26-', (string) $fm['accession'], "Reporion's own accession stays (D20)");

        $noCnp = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:MR:' . self::UID2));
        self::assertStringContainsString('value="POPÉSCU Ana"', $noCnp->body);
        self::assertStringNotContainsString('PACS00042', $noCnp->body, 'not a CNP: never put in the CNP field');

        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:CT:9.9.9'))->status, 'not in the PACS');
        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('nopacs:CT:' . self::UID1))->status, 'a site without a PACS');
        self::assertSame(404, $this->get('owner', '/new?prefill=dicom&ref=mioveni:CT:1.2;rm')->status);
    }

    public function testSeveralStudiesOfOnePatientStartOneMultiExamReportWithAStudyPerExam(): void
    {
        $uid4 = '1.2.826.0.1.3680043.2.1125.4.1';
        $uid5 = '1.2.826.0.1.3680043.2.1125.5.1';
        $this->pacs['10.0.0.5'][] = self::study($uid4, '20260928', '120000', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT CRANIU', 'MV26004', '');
        $this->pacs['10.0.0.5'][] = self::study($uid5, '20260928', '130000', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT GAT', 'MV26005', '');
        $one = 'mioveni:CT:' . self::UID1;
        $two = 'mioveni:CT:' . $uid4;
        foreach (['torace' => 'Torace', 'craniu' => 'Craniu', 'craniu-contrast' => 'Craniu contrast', 'gat' => 'Gat'] as $slug => $title) {
            $this->storage()->create('templates:ct:' . $slug, ['title' => $title, 'visibility' => 'private'], "# {$title}\n", 'owner');
        }

        // The worklist offers the ticks, grouped by what one report can hold
        $list = $this->post('owner', '/x/dicom/worklist', ['site' => 'mioveni', 'modality' => 'CT', 'from' => '2026-09-26', 'to' => '2026-09-29']);
        preg_match_all('/data-ref="([^"]+)" data-group="([^"]+)"/', $list->body, $m);
        $groups = array_combine($m[1], $m[2]);
        self::assertSame($groups[$one], $groups[$two], 'same patient, site, modality and day: one group');
        self::assertNotSame($groups[$one], $groups['mioveni:CT:' . self::UID3], 'another patient: another group');
        self::assertStringNotContainsString('IONESCU', implode(' ', $groups), 'a name never in the group key');

        // The form: the first study fills the report, the others become exams, each with its own study
        $form = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode($two) . ',' . rawurlencode($one));
        self::assertSame(200, $form->status);
        foreach (['name="study_uid" value="' . self::UID1 . '"', 'name="pacs_accession" value="MV26001"', 'value="Ct Torace Nativ"', 'value="10:15"',
            'name="more[0][study_uid]" value="' . $uid4 . '"', 'name="more[0][pacs_accession]" value="MV26004"', 'value="Ct Craniu"'] as $needle) {
            self::assertStringContainsString($needle, $form->body, 'ordered by time: the 10:15 study first, whatever order they were ticked in');
        }
        // Each study its own template, guessed from the PACS description: the exact words win over a longer title
        self::assertMatchesRegularExpression('#<select[^>]*name="template".*?<option value="templates:ct:torace"[^>]* selected#s', $form->body);
        self::assertMatchesRegularExpression('#<select[^>]*name="more\[0\]\[template\]".*?<option value="templates:ct:craniu"[^>]* selected#s', $form->body);

        $created = $this->post('owner', '/new', [
            'guided' => '1', 'action' => 'create', 'name' => 'IONESCU Maria', 'cnp' => $this->cnp, 'date' => '2026-09-28', 'time' => '10:15',
            'modality' => 'CT', 'site' => 'mioveni', 'regions' => ['chest'], 'title' => 'Ct Torace Nativ',
            'study_uid' => self::UID1, 'pacs_accession' => 'MV26001',
            'template' => 'templates:ct:torace',
            'more' => [['title' => 'Ct Craniu', 'regions' => ['neuro'], 'template' => 'templates:ct:craniu', 'study_uid' => $uid4, 'pacs_accession' => 'MV26004']],
        ]);
        self::assertSame(302, $created->status);
        $fm = $this->storage()->read(self::REPORT)->frontmatter;
        self::assertArrayNotHasKey('study_uid', $fm, 'a multi-exam report keeps its studies on its exams');
        self::assertArrayNotHasKey('pacs_accession', $fm);
        self::assertSame(['title', 'modality', 'region', 'study_date', 'template', 'accession', 'study_uid', 'pacs_accession'], array_keys($fm['exams'][0]));
        self::assertSame(['templates:ct:torace', 'templates:ct:craniu'], array_column($fm['exams'], 'template'), 'a template per exam');
        self::assertSame([self::UID1, $uid4], array_column($fm['exams'], 'study_uid'));
        self::assertSame(['MV26001', 'MV26004'], array_column($fm['exams'], 'pacs_accession'));
        self::assertCount(2, array_unique(array_column($fm['exams'], 'accession')), "Reporion's own accession, one per exam (D20)");

        // Either study now has its report, and the PACS tab will not guess an exam for a third
        $after = $this->post('owner', '/x/dicom/worklist', ['site' => 'mioveni', 'modality' => 'CT', 'from' => '2026-09-26', 'to' => '2026-09-29']);
        self::assertSame(2, substr_count($after->body, 'href="/' . self::REPORT . '"'), 'both studies link to the report');
        $page = $this->storage()->read(self::REPORT);
        $refused = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => $uid5]);
        self::assertSame(422, $refused->status);
        self::assertStringContainsString('has several exams', $refused->body);
        self::assertSame(1, $this->storage()->read(self::REPORT)->rev);
    }

    public function testTheNewReportFormOpensTheWorklistFilledWithItsSiteAndModalityButNotRun(): void
    {
        $form = $this->get('owner', '/new?ns=reports:ct:mioveni');
        self::assertMatchesRegularExpression('#data-busy href="/x/dicom/worklist\?site=mioveni&amp;modality=CT&amp;fill=1"#', $form->body, 'from the namespace you came from');

        $this->calls = [];
        $list = $this->get('owner', '/x/dicom/worklist?site=mioveni&modality=CT&fill=1');
        self::assertSame([], $this->calls, 'filled, not run');
        self::assertStringContainsString('<option value="mioveni" selected>', $list->body);
        self::assertStringContainsString('<option value="CT" selected>', $list->body);
        self::assertStringContainsString('then Query', $list->body);
        self::assertStringContainsString('action="/x/dicom/worklist" data-busy', $list->body, 'a spinner on the button while the PACS answers');
    }

    public function testStudiesThatAreNotOneReportAreRefused(): void
    {
        $uid4 = '1.2.826.0.1.3680043.2.1125.4.1';
        $this->pacs['10.0.0.5'][] = self::study($uid4, '20260929', '120000', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT CRANIU', 'MV26004', '');
        $get = fn (string ...$refs): int => $this->get('owner', '/new?prefill=dicom&ref=' . implode(',', array_map('rawurlencode', $refs)))->status;

        self::assertSame(200, $get('mioveni:CT:' . self::UID1, 'mioveni:CT:' . self::UID1), 'a repeated study is one study');
        self::assertSame(404, $get('mioveni:CT:' . self::UID1, 'mioveni:CT:' . self::UID3), 'another patient');
        self::assertSame(404, $get('mioveni:CT:' . self::UID1, 'mioveni:MR:' . self::UID2), 'another modality (and patient)');
        self::assertSame(404, $get('mioveni:CT:' . self::UID1, 'mioveni:CT:' . $uid4), 'another day');
        self::assertSame(404, $get('mioveni:CT:' . self::UID1, 'scuc:CT:' . self::UID1), 'another site');
        self::assertSame(404, $get(...array_map(static fn (int $i): string => 'mioveni:CT:1.2.' . $i, range(1, Pacs::MULTI_MAX + 1))), 'too many');
    }

    public function testThePacsTabLinksTheStudyAndFillsOnlyWhatTheReportLacks(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria'], 'referrer' => 'Dr. Deja',
        ], "# IONESCU Maria\n\n## CT torace\n", 'owner');

        $tab = $this->get('owner', '/x/dicom/study/' . $page->pid);
        self::assertSame(200, $tab->status);
        self::assertContains('StudyDate=20260926-20260930', $this->calls[0], 'the report day ±2 days');
        self::assertContains('ModalitiesInStudy=CT', $this->calls[0], "the report's own modality");
        self::assertCount(1, $this->calls);
        self::assertStringContainsString('same name', $tab->body);
        self::assertStringNotContainsString('DUMITRU', $tab->body, 'only this patient: the PACS was asked for the name');
        self::assertStringNotContainsString('IRM CEREBRAL', $tab->body, 'another modality');
        self::assertSame([['PatientName' => 'IONESCU*']], $this->queryFiles, 'the name went in the query file');
        self::assertStringEndsWith('/query.dcm', $this->calls[0][\count($this->calls[0]) - 1]);
        self::assertStringNotContainsString('IONESCU', implode(' ', $this->calls[0]), 'never on the command line');
        self::assertNotContains('PatientName', $this->calls[0], 'a bare -k PatientName would override the file');

        $done = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1, 'day' => '2026-09-28']);
        self::assertSame(302, $done->status);
        self::assertStringContainsString('done=1', $done->headers['Location']);
        self::assertStringNotContainsString('ionescu', strtolower($done->headers['Location']));

        $updated = $this->storage()->read(self::REPORT);
        self::assertSame(2, $updated->rev);
        $fm = $updated->frontmatter;
        self::assertSame(['name' => 'Ionescu Maria', 'cnp' => $this->cnp, 'sex' => 'F', 'born' => 1980], $fm['patient'], 'blanks filled, the name kept as written');
        self::assertSame('Dr. Deja', $fm['referrer'], 'never overwritten');
        self::assertStringStartsWith('2026-09-28T10:15:00', (string) $fm['study_date'], 'the time added to the same day');
        self::assertSame('Ct Torace Nativ', $fm['exam_title']);
        self::assertSame(self::UID1, $fm['exams'][0]['study_uid']);
        self::assertSame('MV26001', $fm['exams'][0]['pacs_accession']);
        self::assertSame($page->body, $updated->body);

        self::assertStringContainsString('done=0', $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1])->headers['Location']);
        self::assertSame(2, $this->storage()->read(self::REPORT)->rev, 'nothing new: no revision');
        self::assertStringContainsString('ph-link wk-signed-mark" role="img" title="linked"', $this->get('owner', '/x/dicom/study/' . $page->pid)->body);

        $other = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID3]);
        self::assertSame(422, $other->status);
        self::assertStringContainsString('The CNP in the PACS is not the one on this report', $other->body, 'the CNP check comes first');

        $audit = (string) file_get_contents((string) glob($this->dataRoot . '/audit/*.ndjson')[0]);
        self::assertStringContainsString('"via":"dicom"', $audit);
        self::assertStringNotContainsString('ionescu', strtolower($audit), 'no path or name in the audit (invariant 8)');
    }

    public function testThePacsTabAsksForTheCnpFirstThenTheNameAndTheFormIsAPost(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp],
        ], "# IONESCU Maria\n", 'owner');

        $tab = $this->get('owner', '/x/dicom/study/' . $page->pid);

        self::assertSame([['PatientID' => $this->cnp]], $this->queryFiles, 'the CNP first, and it answered: no second query');
        self::assertStringNotContainsString($this->cnp, implode(' ', $this->calls[0]), 'never on a command line');
        self::assertStringContainsString('<form method="post" action="/x/dicom/study/' . $page->pid . '"', $tab->body, 'a POST: no name or CNP in a URL');
        self::assertStringContainsString('name="name" value="Ionescu Maria"', $tab->body, 'prefilled from the report');
        self::assertStringContainsString('name="cnp" value="' . $this->cnp . '"', $tab->body);
        self::assertStringContainsString('same CNP', $tab->body);
        self::assertStringNotContainsString('DUMITRU', $tab->body);

        $this->queryFiles = [];
        $this->calls = [];
        $given = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'day' => '2026-09-28', 'name' => 'Maria Ionescu', 'cnp' => '']);
        self::assertSame(200, $given->status, 'the answer is the page itself, not a redirect');
        self::assertSame([['PatientName' => 'MARIA*'], ['PatientName' => '*IONESCU*']], $this->queryFiles, 'a name written given-name-first: the second try finds it');
        self::assertStringContainsString('IONESCU Maria', $given->body);
        self::assertStringContainsString('same name', $given->body);
    }

    public function testThePacsTabFormCanSearchAnotherPatientAnyDateOrAWholeDay(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria'],
        ], "# IONESCU Maria\n", 'owner');
        $tab = '/x/dicom/study/' . $page->pid;

        $other = $this->post('owner', $tab, ['site' => 'mioveni', 'day' => '', 'name' => 'Dumitru Elena', 'cnp' => '']);
        self::assertSame([['PatientName' => 'DUMITRU*']], $this->queryFiles);
        self::assertSame([], array_filter($this->calls[0], static fn (string $a): bool => str_starts_with($a, 'StudyDate=')), 'an empty day: every date');
        self::assertStringContainsString('DUMITRU Elena', $other->body);

        $this->calls = [];
        $this->queryFiles = [];
        $byCnp = $this->post('owner', $tab, ['site' => 'mioveni', 'day' => '', 'name' => '', 'cnp' => $this->cnp]);
        self::assertSame([['PatientID' => $this->cnp]], $this->queryFiles, 'the CNP alone, any date');
        self::assertSame([], array_filter($this->calls[0], static fn (string $a): bool => str_starts_with($a, 'StudyDate=')));
        self::assertStringContainsString('IONESCU Maria', $byCnp->body);
        self::assertStringNotContainsString('IONESCU Maria</td>', $other->body);

        $this->queryFiles = [];
        $this->calls = [];
        $dayOnly = $this->post('owner', $tab, ['site' => 'mioveni', 'day' => '2026-09-28', 'name' => '', 'cnp' => '']);
        self::assertSame([], $this->queryFiles, 'no name and no CNP: the old day query, nothing patient-shaped sent');
        self::assertContains('StudyDate=20260928', $this->calls[0]);
        self::assertStringContainsString('IONESCU Maria', $dayOnly->body);
        self::assertStringContainsString('DUMITRU Elena', $dayOnly->body, 'the whole day');

        $this->calls = [];
        $nothing = $this->post('owner', $tab, ['site' => 'mioveni', 'day' => '', 'name' => '', 'cnp' => '']);
        self::assertSame([], $this->calls, 'nothing to ask: the PACS is not');
        self::assertSame(422, $nothing->status, 'day, name and CNP all empty: refused');
        self::assertStringContainsString('Give a day, a name or a CNP', $nothing->body);
        self::assertStringNotContainsString('choose the day', $nothing->body, 'not the report-without-a-date message');

        $none = $this->post('owner', $tab, ['site' => 'mioveni', 'day' => '', 'name' => 'Nobody Here', 'cnp' => '']);
        self::assertStringContainsString('has no study for this name or CNP', $none->body);
    }

    public function testTheOwnerCanTurnPatientQueriesOff(): void
    {
        $this->config['plugins']['settings']['dicom']['query_by_patient'] = false;
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp],
        ], "# IONESCU Maria\n", 'owner');

        $tab = $this->get('owner', '/x/dicom/study/' . $page->pid);
        $post = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'day' => '2026-09-28', 'name' => 'Ionescu Maria', 'cnp' => $this->cnp]);

        self::assertSame([], $this->queryFiles, 'date and modality only, as decided first');
        self::assertContains('StudyDate=20260928', $this->calls[0]);
        self::assertStringContainsString('DUMITRU Elena', $tab->body, 'so the whole day is listed');
        self::assertSame(200, $post->status);
    }

    public function testThePatientSearchCentresOnTheReportDayWithAFiveDayWindow(): void
    {
        // No study_date: the yymmdd in the path is the exam day
        $fromPath = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria'],
        ], "# IONESCU Maria\n", 'owner');
        $tab = $this->get('owner', '/x/dicom/study/' . $fromPath->pid);
        self::assertContains('StudyDate=20260926-20260930', $this->calls[0], 'the path day 28 Sep, ±2 days');
        self::assertStringContainsString('name="day" value="2026-09-28"', $tab->body, 'the form shows the centre');
        self::assertStringContainsString('Searched around 2026-09-28, ±2 days.', $tab->body);

        // A report dated the 27th: the PACS study of the 28th is inside the window
        $near = $this->storage()->create('reports:ct:mioveni:260927-ionescu-maria', [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'study_date' => '2026-09-27', 'patient' => ['name' => 'Ionescu Maria'],
        ], "# IONESCU Maria\n", 'owner');
        $this->calls = [];
        $found = $this->get('owner', '/x/dicom/study/' . $near->pid);
        self::assertContains('StudyDate=20260925-20260929', $this->calls[0]);
        self::assertStringContainsString('CT TORACE NATIV', $found->body);

        // Outside it: nothing, and the page says what to do; the window is the owner's setting
        $far = $this->storage()->create('reports:ct:mioveni:260920-ionescu-maria', [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'study_date' => '2026-09-20', 'patient' => ['name' => 'Ionescu Maria'],
        ], "# IONESCU Maria\n", 'owner');
        $this->calls = [];
        $none = $this->get('owner', '/x/dicom/study/' . $far->pid);
        self::assertCount(2, $this->calls, 'both name patterns, on the window only');
        self::assertStringContainsString('within 2 days of the day above', $none->body);

        $this->config['plugins']['settings']['dicom']['search_window_days'] = 9;
        $this->calls = [];
        self::assertStringContainsString('CT TORACE NATIV', $this->get('owner', '/x/dicom/study/' . $far->pid)->body, '20 Sep ±9 days reaches the 28th');
        self::assertContains('StudyDate=20260911-20260929', $this->calls[0]);

        // Empty day: every date; a typed day is a centre too
        $this->calls = [];
        $this->post('owner', '/x/dicom/study/' . $far->pid, ['site' => 'mioveni', 'day' => '', 'name' => 'Ionescu Maria', 'cnp' => '']);
        self::assertSame([], array_filter($this->calls[0], static fn (string $a): bool => str_starts_with($a, 'StudyDate=')));
    }

    public function testAReportLinkedToAnotherStudyIsNotRelinked(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'study_date' => '2026-09-28', 'study_uid' => '1.2.3',
        ], "# IONESCU Maria\n", 'owner');

        $refused = $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1]);

        self::assertSame(422, $refused->status);
        self::assertStringContainsString('already linked to another study', $refused->body);
        self::assertSame(1, $this->storage()->read(self::REPORT)->rev);
    }

    public function testThePacsTabNeedsWriteAccessAndAReport(): void
    {
        $page = $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private'], "# IONESCU Maria\n", 'owner');
        $note = $this->storage()->create('docs:note', ['title' => 'Note', 'visibility' => 'private'], "Text\n", 'owner');

        self::assertSame(404, $this->get('viewer', '/x/dicom/study/' . $page->pid)->status);
        self::assertSame(404, $this->get('owner', '/x/dicom/study/' . $note->pid)->status);
        self::assertSame([], $this->calls, 'the PACS is not asked on a refusal');
        self::assertStringContainsString('/x/dicom/study/' . $page->pid, $this->get('owner', '/' . self::REPORT)->body, 'the PACS tab on the report');
    }

    public function testTheEchoScreenIsTheOwnersAndUsesEchoscuNextToFindscu(): void
    {
        $this->fail['10.0.1.5'] = [1, "E: Association Rejected:\nE: Reason: Called AE Title Not Recognized\n"];

        $page = $this->get('owner', '/x/dicom/echo');

        self::assertSame(200, $page->status);
        self::assertSame('/opt/dcmtk/bin/echoscu', $this->calls[0][0]);
        self::assertSame(['-v', '-aet', 'RP_MIOVENI', '-aec', 'MVPACS'], \array_slice($this->calls[0], 1, 5));
        self::assertStringContainsString('RP_SCUC → SCPACS', $page->body);
        self::assertStringContainsString('answers', $page->body);
        self::assertStringContainsString('The PACS refused us', $page->body);
        self::assertStringContainsString('echoscu log', $page->body, 'a failure shows the log');
        self::assertStringContainsString('Called AE Title Not Recognized', $page->body);
        self::assertSame(1, substr_count($page->body, 'echoscu log'), 'only for the site that failed');
        self::assertSame(404, $this->get('viewer', '/x/dicom/echo')->status);

        // One site: its Test button
        $this->calls = [];
        $one = $this->get('owner', '/x/dicom/echo?site=scuc');
        self::assertCount(1, $this->calls);
        self::assertSame('10.0.1.5', $this->calls[0][\count($this->calls[0]) - 2]);
        self::assertStringContainsString('not tested', $one->body, 'the other site is listed, untested');
        self::assertStringContainsString('/x/dicom/echo?site=mioveni', $one->body, 'each site its own Test button');

        $this->calls = [];
        $none = $this->get('owner', '/x/dicom/echo?site=nopacs');
        self::assertSame([], $this->calls);
        self::assertStringContainsString('Site nopacs has no complete PACS settings saved', $none->body);

        $admin = $this->get('owner', '/admin/plugins');
        self::assertStringContainsString('href="/x/dicom/echo?site=mioveni"', $admin->body, 'a Test button on each site row in Admin');
        self::assertStringContainsString('href="/x/dicom/echo?site=nopacs"', $admin->body);
    }

    public function testTheOwnerSetsThePacsOfEachSiteInAdmin(): void
    {
        $admin = $this->get('owner', '/admin/plugins');
        self::assertStringContainsString('name="servers[mioveni][host]"', $admin->body, 'one row per configured site');
        self::assertStringContainsString('name="servers[nopacs][aet]"', $admin->body);
        self::assertStringContainsString('name="servers[scuc][calling_aet]"', $admin->body, 'our AE title, per site');
        self::assertStringNotContainsString('name="calling_aet"', $admin->body, 'no longer one for all sites');

        $saved = $this->post('owner', '/admin/plugins/dicom/settings', [
            'findscu' => '/usr/local/bin/findscu', 'timeout' => '15', 'modalities' => 'CT, MR', 'lookback_days' => '2', 'search_window_days' => '2', 'query_by_patient' => '1',
            'servers' => [
                'mioveni' => ['host' => '192.168.3.50', 'port' => '104', 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI', 'send_sr' => '1'],
                'scuc' => ['host' => '', 'port' => '', 'aet' => '', 'calling_aet' => ''],
                'gone' => ['host' => '10.9.9.9', 'port' => '104', 'aet' => 'X', 'calling_aet' => 'Y'],
            ],
        ]);
        self::assertSame(302, $saved->status);
        $stored = Yaml::parseFile($this->dataRoot . '/' . InstanceSettings::FILE)['plugins']['settings']['dicom'];
        self::assertSame(['mioveni' => ['host' => '192.168.3.50', 'port' => 104, 'aet' => 'MVPACS', 'calling_aet' => 'RP_MIOVENI', 'send_sr' => true], 'scuc' => ['host' => '', 'port' => 104, 'aet' => '', 'calling_aet' => '', 'send_sr' => false]], $stored['servers'], 'a site not configured is dropped; send SR ticked per site');
        self::assertSame('/usr/local/bin/findscu', $stored['findscu']);

        $bad = ['findscu' => '/usr/bin/findscu', 'timeout' => '15', 'modalities' => 'CT', 'lookback_days' => '2', 'search_window_days' => '2'];
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h', 'port' => '104', 'aet' => 'A', 'calling_aet' => 'TOO LONG AE TITLE XX']]])->status);
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h; rm', 'port' => '104', 'aet' => 'A']]])->status);
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h', 'port' => '104', 'aet' => 'A', 'calling_aet' => '-aec']]])->status, 'never read as an option');
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h', 'port' => '104', 'aet' => 'A\\B', 'calling_aet' => 'X']]])->status, 'the one character DICOM forbids');
        self::assertSame(302, $this->post('owner', '/admin/plugins/dicom/settings', $bad + ['servers' => ['mioveni' => ['host' => 'h', 'port' => '104', 'aet' => 'PACS SRV', 'calling_aet' => 'AE_STROIE@@']]])->status, 'any DICOM AE title: @, inner space');
        self::assertSame(422, $this->post('owner', '/admin/plugins/dicom/settings', ['findscu' => 'findscu'] + $bad)->status, 'a full path');
    }

    public function testNamesAndDatesAreReadTheReporionWay(): void
    {
        self::assertSame('IONESCU Maria Elena', Study::name('ionescu^MARIA^ELENA'));
        self::assertSame('POPA Ion', Study::name('POPA^ION=ポパ^イオン'));
        self::assertSame(['XR'], Study::modalities(['ModalitiesInStudy' => 'CR\\DX\\SR']));
        self::assertSame(['CT'], Study::modalities([], 'CT'), 'not returned: the one queried');
        self::assertSame('2026-09-28 07:05', Study::when(['StudyDate' => '20260928', 'StudyTime' => '070512.123'])?->format('Y-m-d H:i'));
        self::assertTrue(Pacs::sameName('IONESCU Maria', 'Ionescu MARIA'));
        self::assertTrue(Pacs::sameName('POPESCU Ana', 'POPÉSCU Ana'), 'diacritics aside');
        self::assertFalse(Pacs::sameName('IONESCU Maria', 'IONESCU Mara'));
    }

    // The fake findscu/echoscu

    /**
     * @param list<string> $argv
     *
     * @return array{0: int, 1: string}
     */
    private function fakeFindscu(array $argv, int $timeout): array
    {
        $this->calls[] = $argv;
        $file = null;
        if (str_ends_with($argv[\count($argv) - 1], '/query.dcm')) {
            $file = $argv[\count($argv) - 1];
            array_pop($argv);
            self::assertSame(0600, fileperms($file) & 0777, 'the query file is private');
            $this->queryFiles[] = self::decodeDataset((string) file_get_contents($file));
        }
        $host = $argv[\count($argv) - 2];
        if (isset($this->fail[$host])) {
            return $this->fail[$host];
        }
        if (str_ends_with($argv[0], 'echoscu')) {
            return [0, ''];
        }
        $keys = [];
        $dir = '';
        foreach ($argv as $i => $arg) {
            if ($arg === '-k' && str_contains($argv[$i + 1], '=')) {
                [$k, $v] = explode('=', $argv[$i + 1], 2);
                $keys[$k] = $v;
            }
            if ($arg === '-od') {
                $dir = $argv[$i + 1];
            }
        }
        $patient = $file !== null ? end($this->queryFiles) : [];
        $n = 0;
        foreach ($this->pacs[$host] ?? [] as $study) {
            if (isset($patient['PatientID']) && $patient['PatientID'] !== $study['PatientID']) {
                continue;
            }
            if (isset($patient['PatientName']) && preg_match('/^' . str_replace('\\*', '.*', preg_quote($patient['PatientName'], '/')) . '$/', $study['PatientName']) !== 1) {
                continue;
            }
            if (isset($keys['StudyInstanceUID']) && $keys['StudyInstanceUID'] !== $study['StudyInstanceUID']) {
                continue;
            }
            if (isset($keys['ModalitiesInStudy']) && $keys['ModalitiesInStudy'] !== $study['ModalitiesInStudy']) {
                continue;
            }
            if (isset($keys['StudyDate'])) {
                [$from, $to] = array_pad(explode('-', $keys['StudyDate']), 2, null);
                $to ??= $from;
                if ($study['StudyDate'] < $from || $study['StudyDate'] > $to) {
                    continue;
                }
            }
            $xml = '<?xml version="1.0" encoding="ISO-8859-1"?>' . "\n" . '<data-set xfer="1.2.840.10008.1.2.1" name="Little Endian Explicit">' . "\n";
            foreach ($study as $name => $value) {
                $xml .= '<element tag="0000,0000" vr="LO" vm="1" len="' . \strlen($value) . '" name="' . $name . '">' . htmlspecialchars($value, ENT_XML1, 'ISO-8859-1') . "</element>\n";
            }
            file_put_contents(\sprintf('%s/rsp%04d.xml', $dir, ++$n), $xml . "</data-set>\n");
        }

        return [0, ''];
    }

    /**
     * A raw explicit-VR little-endian dataset → keyword => value, for the
     * two patient keys Scu writes.
     *
     * @return array<string, string>
     */
    private static function decodeDataset(string $bytes): array
    {
        $names = [0x00100010 => 'PatientName', 0x00100020 => 'PatientID'];
        $out = [];
        for ($i = 0; $i < \strlen($bytes);) {
            $tag = unpack('vg/ve', substr($bytes, $i, 4));
            $len = unpack('vl', substr($bytes, $i + 6, 2))['l'];
            $out[$names[($tag['g'] << 16) | $tag['e']] ?? 'unknown'] = rtrim(substr($bytes, $i + 8, $len), ' ');
            $i += 8 + $len;
        }

        return $out;
    }

    public function testAnOwnerLinksTheScannerToADeviceAndReportsGetItFromThen(): void
    {
        $this->pacs['10.0.0.5'][0] += ['Manufacturer' => 'SIEMENS', 'ManufacturerModelName' => 'Emotion 16', 'StationName' => 'CTMV01'];
        (new FlatFileUserStore($this->dataRoot))->create('editor', password_hash('x', PASSWORD_ARGON2ID), false, [new Grant('reports', GrantRole::Editor)]);
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-28', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp],
        ], "# IONESCU Maria\n\n## CT torace\n", 'owner');

        $this->post('owner', '/x/dicom/study/' . $page->pid, ['site' => 'mioveni', 'uid' => self::UID1]);
        $fm = Exams::flat($this->storage()->read(self::REPORT)->frontmatter);
        self::assertSame('SIEMENS Emotion 16 / CTMV01', $fm['pacs_device']);
        self::assertSame('', (string) ($fm['device'] ?? ''), 'an unknown scanner: no device guessed');

        $tab = $this->get('owner', '/x/dicom/study/' . $page->pid)->body;
        self::assertStringContainsString('SIEMENS Emotion 16 / CTMV01', $tab);
        self::assertStringContainsString('name="code" value="MV-CT-01"', $tab, "a code in the site's own numbering (its accession code, no device yet)");
        $asEditor = $this->get('editor', '/x/dicom/study/' . $page->pid)->body;
        self::assertStringContainsString('an owner can link it here', $asEditor);
        self::assertStringNotContainsString('name="code"', $asEditor);
        self::assertSame(404, $this->post('editor', '/x/dicom/device/' . $page->pid, ['as' => 'new', 'code' => 'MV-CT-09', 'name' => 'X'])->status, 'the instance settings are an owner\'s (D35)');

        $noName = $this->post('owner', '/x/dicom/device/' . $page->pid, ['as' => 'new', 'code' => 'MV-CT-01', 'name' => '']);
        self::assertSame(422, $noName->status);
        self::assertStringContainsString('Give the new device a name', $noName->body);

        $linked = $this->post('owner', '/x/dicom/device/' . $page->pid, ['as' => 'new', 'code' => 'MV-CT-01', 'name' => 'Mioveni Siemens 16', 'pacs' => 'FORGED']);
        self::assertSame(302, $linked->status);
        self::assertStringEndsWith('?device=1#scanner', $linked->headers['Location']);
        $sites = (new InstanceSettings($this->dataRoot))->load()['sites'];
        self::assertSame(['name' => 'Mioveni Siemens 16', 'pacs' => ['SIEMENS Emotion 16 / CTMV01']], $sites['mioveni']['devices']['MV-CT-01'], "the report's own scanner name, never one from the form");
        self::assertSame('Alt Spital', $sites['scuc']['name'], 'the other sites kept');
        $after = $this->storage()->read(self::REPORT);
        self::assertSame('MV-CT-01', Exams::flat($after->frontmatter)['device'], "this report's blank device filled");
        self::assertSame($page->rev + 2, $after->rev);

        $form = $this->get('owner', '/new?prefill=dicom&ref=' . rawurlencode('mioveni:CT:' . self::UID1))->body;
        self::assertMatchesRegularExpression('#value="MV-CT-01" data-site="mioveni"[^>]* selected#', $form, 'a worklist pick preselects it');
        self::assertStringContainsString('It is MV-CT-01 · Mioveni Siemens 16.', $this->get('owner', '/x/dicom/study/' . $page->pid)->body);

        $taken = $this->post('owner', '/x/dicom/device/' . $page->pid, ['as' => 'new', 'code' => 'mv-ct-01', 'name' => 'Again']);
        self::assertSame(422, $taken->status, 'a code is one device');
    }

    /** @return array<string, string> one study, as the PACS stores it (ISO-8859-1 bytes) */
    private static function study(string $uid, string $date, string $time, string $modality, string $name, string $id, string $description, string $accession, string $referrer): array
    {
        return [
            'SpecificCharacterSet' => 'ISO_IR 100', 'StudyDate' => $date, 'StudyTime' => $time, 'AccessionNumber' => $accession,
            'ReferringPhysicianName' => $referrer, 'StudyDescription' => $description, 'PatientName' => $name, 'PatientID' => $id,
            'PatientBirthDate' => '19800115', 'PatientSex' => 'F', 'StudyInstanceUID' => $uid, 'ModalitiesInStudy' => $modality,
        ];
    }

    /** @param array<string, mixed> $fields */
    private function post(string $user, string $path, array $fields): Response
    {
        return Kernel::boot($this->config)->handle(new Request('POST', $path, cookies: ['reporion' => $this->cookie($user)], body: http_build_query($fields)));
    }

    private function get(string $user, string $path): Response
    {
        [$route, $query] = array_pad(explode('?', $path, 2), 2, '');
        parse_str($query, $params);

        return Kernel::boot($this->config)->handle(new Request('GET', $route, query: array_map('strval', $params), cookies: ['reporion' => $this->cookie($user)]));
    }

    private function cookie(string $user): string
    {
        return (new Session('test-secret', 'reporion', 3600, new FlatFileUserStore($this->dataRoot)))->issue($user);
    }

    public function testBulkLinkLinksTheUnambiguousAndLeavesTheRest(): void
    {
        $storage = $this->storage();
        $cnpReport = 'reports:ct:mioveni:260928-ionescu-maria';
        $nameReport = 'reports:ct:mioveni:260928-dumitru-elena';
        $windowReport = 'reports:ct:mioveni:260929-ionescu-maria';
        $otherSite = 'reports:ct:scuc:260928-ionescu-maria';
        $storage->create($cnpReport, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp]], "# IONESCU Maria\n", 'owner');
        $storage->create($nameReport, ['title' => 'DUMITRU Elena', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Dumitru Elena']], "# DUMITRU Elena\n", 'owner');
        // the patient has a study the day before: inside the PACS tab's window, not the report's day
        $storage->create($windowReport, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp]], "# IONESCU Maria\n", 'owner');
        $storage->create($otherSite, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'scuc', 'patient' => ['name' => 'Ionescu Maria']], "# IONESCU Maria\n", 'owner');

        $check = $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'mioveni'])['report'];
        self::assertSame(2, $check->summary()['would_link']);
        self::assertSame(1, $check->summary()['no_match'], 'the window is not the report day');
        self::assertSame(1, $storage->read($cnpReport)->rev, 'check writes nothing');

        $run = $this->bulk()->run('pacs:link', 'apply', 'owner', ['site' => 'mioveni'])['report'];
        self::assertSame(2, $run->summary()['linked']);
        self::assertSame(self::UID1, $storage->read($cnpReport)->frontmatter['exams'][0]['study_uid']);
        $byName = $storage->read($nameReport);
        self::assertSame(self::UID3, $byName->frontmatter['exams'][0]['study_uid']);
        self::assertSame(CnpTest::make(2, '750310'), $byName->frontmatter['patient']['cnp'], 'the day has one CNP under that name: imported');
        self::assertArrayNotHasKey('study_uid', $storage->read($windowReport)->frontmatter);
        self::assertArrayNotHasKey('study_uid', $storage->read($otherSite)->frontmatter, 'another site is left alone');
        $audit = (string) file_get_contents((string) glob($this->dataRoot . '/audit/*.ndjson')[0]);
        self::assertStringContainsString('"via":"dicom-bulk"', $audit);
        self::assertStringNotContainsString('ionescu', strtolower($audit));
        self::assertSame(0, $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'mioveni'])['report']->summary()['would_link'], 'linked ones are not asked again');
    }

    public function testBulkLinkFillsOnlyThePatientWhenTheDayHoldsSeveralStudiesOfOnePatient(): void
    {
        $storage = $this->storage();
        $this->pacs['10.0.0.5'][] = self::study('1.2.826.0.1.3680043.2.1125.4.1', '20260928', '150000', 'CT', 'IONESCU^MARIA', $this->cnp, 'CT CRANIU', 'MV26004', '');
        $storage->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria']], "# IONESCU Maria\n", 'owner');
        $storage->create('reports:ct:mioveni:260928-dumitru-elena', ['title' => 'DUMITRU Elena', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Dumitru Elena']], "# DUMITRU Elena\n", 'owner');
        // UID3 is already another report's
        $storage->create('reports:ct:scuc:260101-held', ['title' => 'HELD', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'scuc', 'study_uid' => self::UID3], "# HELD\n", 'owner');

        $run = $this->bulk()->run('pacs:link', 'apply', 'owner', ['site' => 'mioveni'])['report'];
        self::assertSame(0, $run->summary()['ambiguous']);
        self::assertSame(1, $run->summary()['patient_only'], 'two studies, one patient');
        self::assertSame(1, $run->summary()['no_match'], 'the only candidate is held elsewhere');
        self::assertSame(0, $run->summary()['linked']);
        $page = $storage->read(self::REPORT);
        self::assertSame(2, $page->rev);
        self::assertArrayNotHasKey('study_uid', $page->frontmatter, 'which study is not known');
        self::assertSame($this->cnp, $page->frontmatter['patient']['cnp'], 'every study of the day agrees on the CNP: imported');
    }

    public function testBulkLinkImportsNoCnpWhenTwoPatientsShareTheNameOnTheDay(): void
    {
        $storage = $this->storage();
        $this->pacs['10.0.0.5'][] = self::study('1.2.826.0.1.3680043.2.1125.5.1', '20260928', '160000', 'CT', 'DUMITRU^ELENA', CnpTest::make(2, '900101'), 'CT CRANIU', 'MV26005', '');
        $storage->create('reports:ct:mioveni:260928-dumitru-elena', ['title' => 'DUMITRU Elena', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Dumitru Elena']], "# DUMITRU Elena\n", 'owner');

        $run = $this->bulk()->run('pacs:link', 'apply', 'owner', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $run->summary()['ambiguous'], 'two patients of that name on the day');
        self::assertArrayNotHasKey('cnp', $storage->read('reports:ct:mioveni:260928-dumitru-elena')->frontmatter['patient']);
    }

    public function testBulkLinkRefreshesAReportThatHoldsItsStudyByUid(): void
    {
        $storage = $this->storage();
        $storage->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'study_uid' => self::UID1, 'patient' => ['name' => 'Ionescu Maria']], "# IONESCU Maria\n", 'owner');

        $check = $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $check->summary()['would_refresh']);
        self::assertSame(1, $storage->read(self::REPORT)->rev);

        $run = $this->bulk()->run('pacs:link', 'apply', 'owner', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $run->summary()['refreshed']);
        $fm = $storage->read(self::REPORT)->frontmatter;
        self::assertSame($this->cnp, $fm['patient']['cnp']);
        self::assertSame('MV26001', $fm['exams'][0]['pacs_accession']);
        self::assertSame(self::UID1, $fm['exams'][0]['study_uid']);
    }

    public function testBulkLinkReturnsASignedReportToDraftAndSaysSo(): void
    {
        $storage = $this->storage();
        $storage->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp]], "# IONESCU Maria\n", 'owner');
        $storage->sign(self::REPORT, 'owner', []);

        $check = $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $check->summary()['would_unsign']);
        self::assertSame('signed', $storage->read(self::REPORT)->status);

        $run = $this->bulk()->run('pacs:link', 'apply', 'owner', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $run->summary()['signed_to_draft']);
        self::assertSame('draft', $storage->read(self::REPORT)->status);
    }

    public function testBulkLinkStopsWhenThePacsDoesNotAnswerAndNeedsAConfiguredSite(): void
    {
        $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria']], "# IONESCU Maria\n", 'owner');
        $this->fail['10.0.0.5'] = [2, "E: Association Request Failed: 0006:031c TCP Initialization Error: Connection refused\n"];
        $run = $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'mioveni'])['report'];
        self::assertSame(1, $run->summary()['error']);
        self::assertSame(1, $run->exit());

        $this->expectException(\InvalidArgumentException::class);
        $this->bulk()->run('pacs:link', 'check', 'cli', ['site' => 'atlantis']);
    }

    public function testTheBulkLinkCommandPrintsEachPatientAndHowItEnded(): void
    {
        $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni', 'patient' => ['name' => 'Ionescu Maria', 'cnp' => $this->cnp]], "# IONESCU Maria\n", 'owner');
        $stdout = fopen('php://memory', 'w+');
        $command = new PluginTaskCommand($this->bulk(), 'pacs:link', ['site', 'limit']);

        self::assertSame(0, $command->run(['--site=mioveni', '--dry-run'], new Output($stdout, fopen('php://memory', 'w+'))));
        rewind($stdout);
        $text = (string) stream_get_contents($stdout);
        self::assertStringContainsString('[1/1] Ionescu Maria … would link (cnp)', $text);

        self::assertSame(1, $command->run(['--site=mioveni'], new Output(fopen('php://memory', 'w+'), fopen('php://memory', 'w+'))), 'writes by default, so it needs an actor');
        self::assertSame(1, $this->storage()->read(self::REPORT)->rev);
        self::assertSame(0, $command->run(['--site=mioveni', '--actor=owner'], new Output(fopen('php://memory', 'w+'), fopen('php://memory', 'w+'))));
        self::assertSame(2, $this->storage()->read(self::REPORT)->rev, 'linked without --dry-run');

        $json = fopen('php://memory', 'w+');
        $command->run(['--site=mioveni', '--dry-run', '--json'], new Output($json, fopen('php://memory', 'w+')));
        rewind($json);
        self::assertStringNotContainsString('Ionescu', (string) stream_get_contents($json), 'the stored/JSON report names pages by pid only');
    }

    /** The runner bin/reporion builds: core tasks plus the ones the plugin's hook offers */
    private function bulk(): MaintenanceRunner
    {
        $index = new Sqlite((string) $this->config['paths']['index'], \dirname(__DIR__, 2) . '/migrations');
        $storage = new FlatFile($this->dataRoot, $index);
        $audit = new AuditLog($this->dataRoot . '/audit');
        $root = \dirname(__DIR__, 2);
        $accessions = new Accessions($this->dataRoot, $index, AccessionFormat::DEFAULT_PATTERN, AccessionFormat::DEFAULT_PAD);
        $newReport = Kernel::newReport($this->config, $root, $index, $storage, $accessions, new SchemaLoader($root . '/conf/schema'));
        $hooks = new Hooks();
        Kernel::loadPlugins($this->config, $root, $storage, $index, $audit, $newReport, new Render(), $hooks);

        return MaintenanceRunner::standard($storage, $index, $audit, $this->dataRoot, 30, $hooks->all('maintenance.tasks'));
    }

    private function storage(): FlatFile
    {
        return new FlatFile($this->dataRoot, new Sqlite((string) $this->config['paths']['index'], \dirname(__DIR__, 2) . '/migrations'));
    }
}
