<?php

// SPDX-License-Identifier: GPL-3.0-or-later

declare(strict_types=1);

namespace Reporion\Tests\Plugin;

use Reporion\Auth\FlatFileUserStore;
use Reporion\Auth\Grant;
use Reporion\Auth\GrantRole;
use Reporion\Http\Request;
use Reporion\Http\Response;
use Reporion\Http\Session;
use Reporion\Index\Sqlite;
use Reporion\Kernel;
use Reporion\Plugin\Hipobridge\Fhir;
use Reporion\Plugin\Hipobridge\Plugin;
use Reporion\Plugin\Loader;
use Reporion\Storage\FlatFile;
use Reporion\Tests\Http\HttpTestCase;
use Reporion\Tests\Support\CnpTest;

/**
 * plugins/hipobridge against a fake HippoBridge (the FHIR shapes its
 * hippoclient.py produces). Every name, CNP and id is made up; the CNPs are
 * generated by the checksum rule (invariant 10).
 */
final class HipobridgeTest extends HttpTestCase
{
    private const REPORT = 'reports:ct:mioveni:260920-ionescu-maria';

    private string $cnp;

    /** @var list<string> the paths the fake HIS was asked for, with their queries */
    private array $asked = [];

    /** @var array<string, array{0: int, 1: mixed}> path?query → status, JSON */
    private array $his = [];

    protected function setUp(): void
    {
        parent::setUp();
        Loader::registerAutoload(\dirname(__DIR__, 2) . '/plugins', 'hipobridge');
        $this->cnp = CnpTest::make(2, '800115');
        $this->config['sites'] = ['mioveni' => ['name' => 'Spital Test', 'accession_code' => 'MV', 'devices' => []]];
        $this->config['plugins'] = [
            'enabled' => ['hipobridge'],
            'settings' => ['hipobridge' => ['url' => 'http://his.test', 'username' => 'svc', 'password' => 'pw', 'site' => 'mioveni']],
        ];
        $users = new FlatFileUserStore($this->dataRoot);
        $users->create('owner', password_hash('x', PASSWORD_ARGON2ID), true);
        $users->create('viewer', password_hash('x', PASSWORD_ARGON2ID), false, [new Grant('reports', GrantRole::Viewer)]);
        Plugin::$transport = function (string $url, array $headers, int $timeout): array {
            self::assertContainsEquals('Authorization: Basic ' . base64_encode('svc:pw'), $headers);
            $key = substr($url, \strlen('http://his.test'));
            $this->asked[] = $key;
            [$status, $json] = $this->his[$key] ?? $this->his[strtok($key, '?')] ?? [404, null];

            return [$status, (string) json_encode($json)];
        };
    }

    protected function tearDown(): void
    {
        Plugin::$transport = null;
        parent::tearDown();
    }

    public function testTheWorklistListsPerformedExamsPerModalityAndMarksReportedOnes(): void
    {
        $this->his['/fhir/Schedule'] = [200, self::bundle([
            self::scheduled('1001', 'IONESCU MARIA', 'ct', 'completed', '2026-09-20 10:15'),
            self::scheduled('1002', 'POPA ION', 'ct', 'revoked', '2026-09-20 11:00'),
            self::scheduled('1003', 'DUMITRU ELENA', 'irm', 'active', '2026-09-21 08:00', 'Cefalee.'),
        ])];
        $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private', 'order_ref' => 'hipobridge:ServiceRequest/1001'], "# IONESCU Maria\n", 'owner');

        $page = $this->get('owner', '/x/hipobridge/worklist');

        self::assertSame(200, $page->status);
        self::assertCount(2, array_filter($this->asked, static fn (string $a): bool => str_starts_with($a, '/fhir/Schedule?')), 'one query per modality (ct, irm)');
        self::assertStringContainsString('lab_id=26', implode(' ', $this->asked));
        self::assertStringContainsString('status=active%2Ccompleted%2Cended', implode(' ', $this->asked));
        self::assertStringContainsString('DUMITRU Elena', $page->body);
        self::assertStringNotContainsString('POPA', $page->body, 'a revoked order is not a performed exam');
        self::assertStringContainsString('/new?prefill=hipobridge&amp;ref=irm.1003', $page->body);
        self::assertStringContainsString('href="/' . self::REPORT . '"', $page->body, 'already reported: a link, not a second report');
        self::assertSame(1, substr_count($page->body, 'IONESCU Maria'), 'deduplicated across the two queries');
        self::assertStringContainsString('21 Sep 2026, 08:00', $page->body, 'a readable date, never raw ISO');
        self::assertStringContainsString('Dr. Sectie<div class="wk-text-sm">Cefalee.</div>', $page->body, 'the indication under the requester');
        self::assertSame(2, substr_count($page->body, '>MEDICALA<'), 'the ward stays the ward when an indication note comes first');
        self::assertStringContainsString('data-busy href="/new?prefill=hipobridge&amp;ref=irm.1003"', $page->body, 'a spinner while the order is read');
        self::assertStringContainsString('>Manual</a>', $page->body);

        self::assertSame(404, $this->get('viewer', '/x/hipobridge/worklist')->status);
    }

    public function testTheWorklistSaysWhenTheHisCannotBeReached(): void
    {
        Plugin::$transport = static fn (): array => [0, ''];

        $page = $this->get('owner', '/x/hipobridge/worklist');

        self::assertSame(200, $page->status);
        self::assertStringContainsString('HippoBridge did not answer.', $page->body);
    }

    public function testStartingAReportFillsTheGuidedFormFromTheOrder(): void
    {
        $this->his['/fhir/ServiceRequest/1001'] = [200, self::order('1001', 'IONESCU MARIA', $this->cnp, '2026-09-20T10:15:00', 'CT TORACE', 'Chest', 'Tuse persistenta.', 'Dr. Test')];

        $form = $this->get('owner', '/new?prefill=hipobridge&ref=ct.1001');

        self::assertSame(200, $form->status);
        foreach (['value="IONESCU Maria"', 'value="' . $this->cnp . '"', 'value="2026-09-20"', 'value="10:15"', 'value="Ct Torace"', 'Dr. Test', 'Tuse persistenta.', 'name="order_ref" value="hipobridge:ServiceRequest/1001"'] as $needle) {
            self::assertStringContainsString($needle, $form->body);
        }
        self::assertMatchesRegularExpression('/value="chest"[^>]*checked/', $form->body, 'Chest → the chest region');
        self::assertSame(404, $this->get('owner', '/new?prefill=hipobridge&ref=../1001')->status);
        self::assertSame(404, $this->get('owner', '/new?prefill=hipobridge&ref=ct.9999')->status, 'an order the HIS does not have');
    }

    public function testPriorsImportsTheChosenReportsAndFillsOnlyWhatTheReportLacks(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'site' => 'mioveni',
            'study_date' => '2026-09-20', 'patient' => ['name' => 'IONESCU Maria'], 'indication' => 'Already written.',
        ], "# IONESCU Maria\n\n## CT torace\n", 'owner');
        $this->his['/fhir/Patient?q=IONESCU+Maria'] = [200, self::bundle([self::patientShort('p7', 'IONESCU MARIA'), self::patientShort('p8', 'IONESCU MARIA')])];
        $this->his['/fhir/Patient/p7'] = [200, self::patient('p7', 'IONESCU', 'MARIA', $this->cnp)];
        $this->his['/fhir/ServiceRequest?patient=p7'] = [200, self::bundle([
            self::request('1001', 'ct', '2026-09-20 10:15', ['Chest']),
            self::request('900', 'irm', '2025-03-02 09:00', ['Brain'], 'Vertij.'),
            self::request('800', 'eco', '2024-01-10 12:00', ['Abdomen']),
            self::request('700', 'lab', '2024-01-10 12:00', []),
        ])];
        $this->his['/fhir/ServiceRequest/1001'] = [200, self::order('1001', 'IONESCU MARIA', $this->cnp, '2026-09-20T10:15:00', 'CT TORACE', 'Chest', 'Tuse persistenta.', 'Dr. Trimitator')];
        $this->his['/fhir/DiagnosticReport/900'] = [200, self::report('900', '2025-03-02T09:30:00', [['IRM cerebral', "Fara leziuni.\n\nConcluzii: normal.", 'irm', 'Brain', 'Dr. Alt Radiolog']])];
        $this->his['/fhir/DiagnosticReport/800'] = [200, self::report('800', '2024-01-10T12:00:00', [])];

        $choose = $this->get('owner', '/x/hipobridge/priors/' . $page->pid);
        self::assertSame(200, $choose->status);
        self::assertStringContainsString('Several patients match', $choose->body, 'two name matches, no CNP on the report: the user picks');
        self::assertStringContainsString('?patient=p7', $choose->body);

        $list = $this->get('owner', '/x/hipobridge/priors/' . $page->pid . '?patient=p7');
        self::assertSame(200, $list->status);
        self::assertStringNotContainsString('value="lab.700"', $list->body, 'only the configured exam types');
        self::assertMatchesRegularExpression('/name="this" value="ct\.1001" checked/', $list->body, 'same day, same modality: this report\'s own exam');
        self::assertMatchesRegularExpression('/name="import\[\]" value="irm\.900" checked/', $list->body);
        self::assertStringNotContainsString($this->cnp, $list->body, 'the CNP is only said to be present');
        self::assertStringContainsString('02 Mar 2025, 09:00', $list->body);
        self::assertStringContainsString('Dr. X<br><small>Vertij.</small>', $list->body);
        self::assertStringContainsString('data-check-all="import[]"', $list->body, 'select all, under the import column');
        self::assertMatchesRegularExpression('#<a class="wk-tab" data-busy data-on="1" aria-current="page" href="/x/hipobridge/priors/' . $page->pid . '">HippoBridge</a>#', $list->body, 'its own tab, current');
        self::assertStringContainsString('<label class="radio"><input type="checkbox" name="import[]"', $list->body, "the app's checkboxes");

        $view = $this->get('owner', '/' . self::REPORT)->body;
        self::assertStringContainsString('href="/x/hipobridge/priors/' . $page->pid . '">HippoBridge</a>', $view, 'the tab on the report');
        self::assertStringNotContainsString('Priors from', $view, 'no menu entry any more');
        self::assertStringNotContainsString('/x/hipobridge/', $this->get('viewer', '/' . self::REPORT)->body, 'writers only');

        $done = $this->post('owner', '/x/hipobridge/priors/' . $page->pid, ['patient' => 'p7', 'import' => ['irm.900', 'eco.800'], 'this' => 'ct.1001']);
        self::assertSame(302, $done->status);
        self::assertStringContainsString('done=1.1.1.0', $done->headers['Location'], 'one imported, one without text yet, the report updated, none already there');
        self::assertStringNotContainsString('ionescu', strtolower($done->headers['Location']), 'no name in the URL (D1)');

        $prior = $this->storage()->read('reports:mri:mioveni:250302-ionescu-maria');
        self::assertSame('archived', $prior->status, "another radiologist's report: never signed here");
        $fm = $prior->frontmatter;
        self::assertSame(['MR'], $fm['modality']);
        self::assertSame(['neuro'], $fm['region']);
        self::assertSame('IRM cerebral', $fm['exam_title']);
        self::assertSame('Dr. Alt Radiolog', $fm['radiologist']);
        self::assertSame('hipobridge:ServiceRequest/900', $fm['order_ref']);
        self::assertSame('hipobridge:DiagnosticReport/900', $fm['imported_from']);
        self::assertSame(['name' => 'IONESCU Maria', 'sex' => 'F', 'born' => 1980, 'cnp' => $this->cnp], $fm['patient']);
        self::assertStringStartsWith('2025-03-02T09:30:00', (string) $fm['study_date']);
        self::assertSame("# IONESCU Maria\n\n## IRM cerebral\n\nFara leziuni.\n\nConcluzii: normal.\n", $prior->body);

        $updated = $this->storage()->read(self::REPORT);
        self::assertSame(2, $updated->rev);
        $fm = $updated->frontmatter;
        self::assertSame(['name' => 'IONESCU Maria', 'cnp' => $this->cnp, 'sex' => 'F', 'born' => 1980], $fm['patient'], 'the blanks, filled; the name kept');
        self::assertSame('Already written.', $fm['indication'], 'never overwritten');
        self::assertSame('Dr. Trimitator', $fm['referrer']);
        self::assertSame('Ct Torace', $fm['exam_title']);
        self::assertSame(['chest'], $fm['region']);
        self::assertSame(['CT'], $fm['modality']);
        self::assertSame('mioveni', $fm['site']);
        self::assertStringStartsWith('2026-09-20T10:15:00', (string) $fm['study_date'], "the order's time added to the report's own day");
        self::assertSame('hipobridge:ServiceRequest/1001', $fm['order_ref']);
        self::assertSame(['reports:mri:mioveni:250302-ionescu-maria'], $fm['priors']);
        self::assertSame($page->body, $updated->body);

        // Again: the prior is already in the wiki — linked, not imported twice
        $again = $this->post('owner', '/x/hipobridge/priors/' . $page->pid, ['patient' => 'p7', 'import' => ['irm.900'], 'this' => 'ct.1001']);
        self::assertStringContainsString('done=0.0.0.1', $again->headers['Location'], 'one already in the wiki: linked');
        self::assertSame(2, $this->storage()->read(self::REPORT)->rev, 'nothing new: no revision');

        $audit = (string) file_get_contents((string) glob($this->dataRoot . '/audit/*.ndjson')[0]);
        self::assertStringContainsString('"via":"hipobridge"', $audit);
        self::assertStringNotContainsString('ionescu', strtolower($audit), 'no path or name in the audit (invariant 8)');
        foreach ($this->asked as $asked) {
            self::assertStringNotContainsString('POST', $asked);
        }
    }

    public function testTheFillNeverContradictsWhereTheReportIsFiled(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'patient' => ['name' => 'IONESCU Maria', 'cnp' => $this->cnp],
        ], "# IONESCU Maria\n", 'owner');
        $this->his['/fhir/Patient/p7'] = [200, self::patient('p7', 'IONESCU', 'MARIA', $this->cnp)];
        $this->his['/fhir/ServiceRequest?patient=p7'] = [200, self::bundle([self::request('900', 'irm', '2025-03-02 09:00', ['Brain'])])];
        $this->his['/fhir/ServiceRequest/900'] = [200, self::order('900', 'IONESCU MARIA', $this->cnp, '2025-03-02T09:00:00', 'IRM CEREBRAL', 'Brain', 'Vertij.', 'Dr. Neuro')];

        // The user says the report answers an MR exam of another day, but it is filed as a CT of 2026-09-20
        $done = $this->post('owner', '/x/hipobridge/priors/' . $page->pid, ['patient' => 'p7', 'this' => 'irm.900']);
        self::assertSame(302, $done->status, strip_tags($done->body));

        $fm = $this->storage()->read(self::REPORT)->frontmatter;
        self::assertSame('Dr. Neuro', $fm['referrer']);
        self::assertSame('Vertij.', $fm['indication']);
        self::assertSame('Irm Cerebral', $fm['exam_title']);
        self::assertSame(['neuro'], $fm['region']);
        self::assertArrayNotHasKey('study_date', $fm, "another day than the path's");
        self::assertArrayNotHasKey('modality', $fm, "MR is not the path's ct namespace");
        self::assertArrayNotHasKey('site', $fm, 'the site is never written');
    }

    public function testADifferentCnpInTheHisStopsTheImport(): void
    {
        $page = $this->storage()->create(self::REPORT, [
            'title' => 'IONESCU Maria', 'visibility' => 'private', 'modality' => ['CT'], 'study_date' => '2026-09-20',
            'patient' => ['name' => 'IONESCU Maria', 'cnp' => $this->cnp],
        ], "# IONESCU Maria\n", 'owner');
        $other = CnpTest::make(2, '810220');
        $this->his['/fhir/Patient?q=' . $this->cnp] = [200, self::patient('p9', 'IONESCU', 'MARIA', $other)];
        $this->his['/fhir/ServiceRequest?patient=p9'] = [200, self::bundle([self::request('900', 'irm', '2025-03-02 09:00', ['Brain'])])];

        $list = $this->get('owner', '/x/hipobridge/priors/' . $page->pid);
        self::assertStringContainsString('The CNP in HippoBridge is not the one on this report', $list->body);
        self::assertStringNotContainsString('name="import[]"', $list->body);

        $refused = $this->post('owner', '/x/hipobridge/priors/' . $page->pid, ['patient' => 'p9', 'import' => ['irm.900']]);
        self::assertSame(422, $refused->status);
        self::assertSame(1, $this->storage()->read(self::REPORT)->rev);
    }

    public function testPriorsNeedWriteAccessToTheReport(): void
    {
        $page = $this->storage()->create(self::REPORT, ['title' => 'IONESCU Maria', 'visibility' => 'private'], "# IONESCU Maria\n", 'owner');
        $note = $this->storage()->create('docs:note', ['title' => 'Note', 'visibility' => 'private'], "Text\n", 'owner');

        self::assertSame(404, $this->get('viewer', '/x/hipobridge/priors/' . $page->pid)->status);
        self::assertSame(404, $this->get('owner', '/x/hipobridge/priors/' . $note->pid)->status, 'reports only');
        self::assertSame(404, $this->get('owner', '/x/hipobridge/priors/01NOSUCHPID')->status);
        self::assertSame([], $this->asked, 'the HIS is not asked on a refusal');
    }

    public function testNamesAndRegionsAreReadTheReporionWay(): void
    {
        self::assertSame('POPESCU Ana-Maria Elena', Fhir::displayName('popescu  ANA-MARIA elena'));
        self::assertSame('chest', Fhir::region('Chest'));
        self::assertSame('abdomen', Fhir::region('urinary_tract'));
        self::assertNull(Fhir::region('Unknown'));
    }

    // Fake HippoBridge resources — the shapes of hippoclient.py's fhir_response()s

    /** @param list<array<string, mixed>> $resources */
    private static function bundle(array $resources): array
    {
        return ['resourceType' => 'Bundle', 'type' => 'searchset', 'total' => \count($resources), 'entry' => array_map(static fn (array $r): array => ['resource' => $r], $resources)];
    }

    private static function scheduled(string $id, string $name, string $modality, string $status, string $when, string $indication = ''): array
    {
        $notes = [['text' => 'MEDICALA']];
        if ($indication !== '') {
            array_unshift($notes, ['text' => $indication, 'category' => [['text' => 'clinical-indication']]]);
        }

        return ['resourceType' => 'ServiceRequest', 'id' => $id, 'status' => $status, 'intent' => 'order', 'identifier' => [['value' => 'R' . $id]],
            'subject' => ['display' => $name], 'category' => [['coding' => [['code' => $modality]]]], 'authoredOn' => $when,
            'requester' => ['display' => 'Dr. Sectie'], 'note' => $notes];
    }

    private static function order(string $id, string $name, string $cnp, string $when, string $procedure, string $region, string $indication, string $requester): array
    {
        return ['resourceType' => 'ServiceRequest', 'id' => $id, 'status' => 'active', 'intent' => 'order',
            'subject' => ['display' => '46 ani', 'identifier' => ['system' => 'http://h/fhir/NamingSystem/patient-cnp', 'value' => $cnp]],
            'extension' => [['url' => 'patientName', 'valueString' => $name]],
            'code' => ['text' => $procedure], 'bodySite' => [['text' => $region]], 'requester' => ['display' => $requester],
            'note' => [['text' => 'MEDICALA'], ['text' => $indication, 'category' => [['text' => 'clinical-indication']]]], 'authoredOn' => $when];
    }

    private static function patientShort(string $id, string $name): array
    {
        return ['resourceType' => 'Patient', 'id' => $id, 'name' => [['use' => 'official', 'text' => $name]], 'gender' => 'female', 'birthDate' => '1980-01-15'];
    }

    private static function patient(string $id, string $family, string $given, string $cnp): array
    {
        return ['resourceType' => 'Patient', 'id' => $id, 'name' => [['use' => 'official', 'family' => $family, 'given' => [$given]]], 'gender' => 'female',
            'identifier' => [['use' => 'official', 'system' => 'http://h/fhir/NamingSystem/patient-cnp', 'value' => $cnp]]];
    }

    /** @param list<string> $regions */
    private static function request(string $id, string $type, string $when, array $regions, string $indication = ''): array
    {
        return ['resourceType' => 'ServiceRequest', 'id' => $id, 'status' => 'active', 'intent' => 'order', 'subject' => ['reference' => 'Patient/p'],
            'code' => ['coding' => [['code' => $type, 'display' => strtoupper($type)]]], 'authoredOn' => $when, 'requester' => ['display' => 'Dr. X'],
            'bodySite' => array_map(static fn (string $r): array => ['text' => $r], $regions)]
            + ($indication !== '' ? ['note' => [['text' => $indication, 'category' => [['text' => 'clinical-indication']]]]] : []);
    }

    /** @param list<array{0: string, 1: string, 2: string, 3: string, 4: string}> $forms */
    private static function report(string $id, string $when, array $forms): array
    {
        return ['resourceType' => 'DiagnosticReport', 'id' => $id, 'status' => 'final', 'effectiveDateTime' => $when,
            'presentedForm' => array_map(static fn (array $f): array => ['contentType' => 'text/markdown', 'title' => $f[0], 'data' => $f[1], 'type' => $f[2], 'region' => $f[3], 'validator' => $f[4]], $forms)];
    }

    /** @param array<string, mixed> $fields */
    private function post(string $user, string $path, array $fields): Response
    {
        return Kernel::boot($this->config)->handle(new Request('POST', $path, cookies: ['reporion' => $this->cookie($user)], body: http_build_query($fields)));
    }

    private function get(string $user, string $path): Response
    {
        [$route, $query] = array_pad(explode('?', $path, 2), 2, '');
        parse_str($query, $params);

        return Kernel::boot($this->config)->handle(new Request('GET', $route, query: array_map('strval', $params), cookies: ['reporion' => $this->cookie($user)]));
    }

    private function cookie(string $user): string
    {
        return (new Session('test-secret', 'reporion', 3600, new FlatFileUserStore($this->dataRoot)))->issue($user);
    }

    private function storage(): FlatFile
    {
        return new FlatFile($this->dataRoot, new Sqlite((string) $this->config['paths']['index'], \dirname(__DIR__, 2) . '/migrations'));
    }
}
