<?php

// SPDX-License-Identifier: GPL-3.0-or-later

declare(strict_types=1);

namespace Reporion\Tests\Http;

use Reporion\Auth\FlatFileUserStore;
use Reporion\Auth\Grant;
use Reporion\Auth\GrantRole;
use Reporion\Http\Request;
use Reporion\Http\Response;
use Reporion\Http\Session;
use Reporion\Index\Sqlite;
use Reporion\Kernel;
use Reporion\Storage\FlatFile;
use Reporion\Tests\Support\CnpTest;

/**
 * The guided new-report form (roadmap phase 7). Every name and CNP here is
 * made up; the CNPs are generated by the checksum rule (invariant 10).
 */
final class NewReportTest extends HttpTestCase
{
    private const PATH = 'reports:mri:mioveni:260926-popescu-ana-maria';

    protected function setUp(): void
    {
        parent::setUp();
        $users = new FlatFileUserStore($this->dataRoot);
        $users->create('owner', password_hash('x', PASSWORD_ARGON2ID), true);
        $users->create('ct-editor', password_hash('x', PASSWORD_ARGON2ID), false, [new Grant('reports:ct', GrantRole::Editor)]);
        $this->config['sites'] = [
            'mioveni' => ['name' => 'Spital Test', 'accession_code' => 'MV', 'devices' => ['MV-MR-01' => 'Aparat RM', 'MV-CT-01' => 'Aparat CT']],
            'scuc' => ['name' => 'Alt Spital', 'devices' => ['SC-MR-01' => 'Alt RM']],
        ];
    }

    public function testACompleteFormCreatesTheReportWithItsPathFrontmatterAndAccession(): void
    {
        $cnp = CnpTest::make(2, '800115');
        $this->storage()->create('templates:mri:lombar', [
            'title' => 'RM coloana lombara', 'visibility' => 'private', 'protocol' => 'spine-lumbar-v2',
            'patient' => ['name' => 'NU SE COPIAZA'], 'accession' => 'X-1',
        ], "## Tehnica\n\nSecvente standard.\n", 'owner');

        $response = $this->post('owner', [
            'action' => 'create', 'name' => 'POPESCU  Ana Maria', 'cnp' => $cnp, 'sex' => '', 'born' => '',
            'date' => '2026-09-26', 'time' => '09:30', 'modality' => 'MR', 'site' => 'mioveni', 'device' => 'MV-MR-01',
            'regions' => ['spine'], 'referrer' => 'dr. Test', 'indication' => 'Lombalgie.', 'template' => 'templates:mri:lombar', 'title' => '',
        ]);

        self::assertSame(302, $response->status);
        self::assertStringEndsWith('/' . self::PATH . '/edit', $response->headers['Location']);
        $page = $this->storage()->read(self::PATH);
        $fm = $page->frontmatter;
        self::assertSame(['title', 'exam_title', 'visibility', 'modality', 'region', 'site', 'device', 'study_date', 'accession', 'patient', 'referrer', 'indication', 'protocol', 'template'], array_keys($fm));
        self::assertSame('POPESCU Ana Maria', $fm['title'], 'titled by the patient (D30 as amended)');
        self::assertSame('RM coloana lombara', $fm['exam_title'], "the template's title, for exports");
        self::assertSame('private', $fm['visibility']);
        self::assertSame(['MR'], $fm['modality']);
        self::assertSame(['spine'], $fm['region']);
        self::assertSame('MV-MR-01', $fm['device']);
        self::assertStringStartsWith('2026-09-26T09:30:00', (string) $fm['study_date']);
        self::assertSame('MV-MR-26-0001', $fm['accession']);
        self::assertSame(['name' => 'POPESCU Ana Maria', 'sex' => 'F', 'born' => 1980, 'cnp' => $cnp], $fm['patient'], 'from the CNP; never the template\'s patient');
        self::assertSame('spine-lumbar-v2', $fm['protocol']);
        self::assertSame('templates:mri:lombar', $fm['template']);
        self::assertSame("# POPESCU Ana Maria\n\n## RM coloana lombara\n", $page->body, "the patient's name heads the text, the exam its part (FORMATS.md §11); the template's text is not copied");
        self::assertSame('draft', $page->status);

        $audit = (string) file_get_contents($this->dataRoot . '/audit/' . date('Y-m') . '.ndjson');
        self::assertStringContainsString('"action":"page.create"', $audit);
        self::assertStringNotContainsString('popescu', strtolower($audit), 'path_hash only (invariant 8)');
        self::assertStringNotContainsString($cnp, $audit);
    }

    /** Several imported templates share an exam title: the picker lists them by their catalogue label */
    public function testThePickerListsTemplatesByTheirCatalogueLabel(): void
    {
        $this->storage()->create('templates:ct:abdomen-normal', ['title' => 'CT Abdomen', 'visibility' => 'private', 'template_label' => 'Abdomen: CT Normal'], "x\n", 'owner');
        $this->storage()->create('templates:ct:abdomen-tumoral', ['title' => 'CT Abdomen', 'visibility' => 'private', 'template_label' => 'Abdomen: CT Tumoral'], "x\n", 'owner');
        $this->storage()->create('templates:ct:plain', ['title' => 'CT Plain', 'visibility' => 'private'], "x\n", 'owner');

        $body = $this->get('owner', '/new')->body;

        self::assertStringContainsString('<b>Abdomen: CT Normal</b>', $body);
        self::assertStringContainsString('<b>Abdomen: CT Tumoral</b>', $body);
        self::assertStringContainsString('<b>CT Plain</b>', $body, 'no label: the title');
    }

    public function testPreviewShowsThePathAndNextAccessionAndCreatesNothing(): void
    {
        $this->storage()->create('reports:mri:mioveni:old', ['title' => 'Old', 'visibility' => 'private', 'accession' => 'MV-MR-26-0041'], "x\n", 'owner');

        $response = $this->post('owner', ['action' => 'preview'] + $this->minimal());

        self::assertSame(200, $response->status);
        self::assertStringContainsString(self::PATH, $response->body);
        self::assertStringContainsString('MV-MR-26-0042', $response->body, 'above the numbers already issued');
        self::assertFalse($this->exists(self::PATH));
    }

    public function testBadInputIsRefusedFieldByFieldAndNothingIsCreated(): void
    {
        $valid = CnpTest::make(1, '800115');
        $badCnp = substr($valid, 0, 12) . (((int) $valid[12] + 1) % 10);
        $response = $this->post('owner', ['action' => 'create', 'cnp' => $badCnp] + $this->minimal());
        self::assertSame(422, $response->status);
        self::assertStringContainsString('This CNP is not valid', $response->body);

        $mismatch = $this->post('owner', ['action' => 'create', 'cnp' => CnpTest::make(2, '800115'), 'sex' => 'M'] + $this->minimal());
        self::assertSame(422, $mismatch->status);
        self::assertStringContainsString('The CNP says otherwise', $mismatch->body);

        $device = $this->post('owner', ['action' => 'create', 'device' => 'SC-MR-01'] + $this->minimal());
        self::assertStringContainsString('does not belong to the chosen site', $device->body);

        self::assertFalse($this->exists(self::PATH));
    }

    public function testASecondReportForTheSamePatientAndDateNeedsAConfirm(): void
    {
        self::assertSame(302, $this->post('owner', ['action' => 'create'] + $this->minimal())->status);

        $again = $this->post('owner', ['action' => 'create'] + $this->minimal());
        self::assertSame(200, $again->status);
        self::assertStringContainsString('already has a report on this date', $again->body);
        self::assertFalse($this->exists(self::PATH . '-2'));

        $confirmed = $this->post('owner', ['action' => 'create', 'confirm_same_day' => '1'] + $this->minimal());
        self::assertStringEndsWith('/' . self::PATH . '-2/edit', $confirmed->headers['Location'], 'the -2 collision suffix (FORMATS §1)');
        self::assertSame('MV-MR-26-0002', $this->storage()->read(self::PATH . '-2')->frontmatter['accession']);
    }

    public function testAnEditorCreatesOnlyWhereTheyMayWrite(): void
    {
        self::assertStringContainsString('name="guided" value="1"', $this->get('ct-editor', '/new')->body);

        $mr = $this->post('ct-editor', ['action' => 'create'] + $this->minimal());
        self::assertSame(422, $mr->status);
        self::assertStringContainsString('cannot create reports for this modality and site', $mr->body);

        $ct = $this->post('ct-editor', ['action' => 'create', 'modality' => 'CT', 'device' => 'MV-CT-01'] + $this->minimal());
        self::assertStringEndsWith('/reports:ct:mioveni:260926-popescu-ana-maria/edit', $ct->headers['Location']);
    }

    /**
     * The name titles the report on screen; exports, the public view and a
     * duplicate carry the exam title and no name heading (invariant 8).
     */
    public function testThePatientNameStaysOffExportsPublicViewsAndCopies(): void
    {
        $this->post('owner', ['action' => 'create', 'title' => 'IRM Cerebral'] + $this->minimal());
        $page = $this->storage()->read(self::PATH);
        self::assertSame(['POPESCU Ana Maria', 'IRM Cerebral'], [$page->frontmatter['title'], $page->frontmatter['exam_title']]);

        self::assertStringContainsString('POPESCU Ana Maria', $this->get('owner', '/' . self::PATH)->body, 'on screen, for staff');

        $print = $this->get('owner', '/export/' . self::PATH . '.html')->body;
        self::assertStringContainsString('<h1 class="doc-title">IRM Cerebral</h1>', $print);
        self::assertStringNotContainsString('<h1 id="popescu-ana-maria"', $print, 'no name heading in the text');

        $storage = $this->storage();
        $storage->save(self::PATH, ['visibility' => 'public'] + $page->frontmatter, $page->body . "\n## Descriere\n\nText.\n", $page->rev, 'owner');
        $public = Kernel::boot($this->config)->handle(new Request('GET', '/' . self::PATH))->body;
        self::assertStringContainsString('<h1 class="wk-doc-title">IRM Cerebral</h1>', $public);
        self::assertStringNotContainsString('<h1 id="popescu-ana-maria"', $public);

        $copy = json_decode(Kernel::boot($this->config)->handle(new Request('POST', '/api/v1/pages/' . self::PATH . '/duplicate', cookies: ['reporion' => $this->cookie('owner')], body: (string) json_encode(['to' => 'docs:caz-didactic'])))->body, true);
        $duplicate = $storage->read((string) $copy['path']);
        self::assertSame('IRM Cerebral', $duplicate->frontmatter['title']);
        self::assertStringNotContainsString('POPESCU', $duplicate->body);
    }

    public function testPlusExamAddsARowAndRemoveTakesItAwayWithoutCreating(): void
    {
        $added = $this->post('owner', ['action' => 'add_exam'] + $this->minimal());
        self::assertSame(200, $added->status);
        self::assertStringContainsString('name="more[0][title]"', $added->body);
        self::assertStringNotContainsString('name="more[1][title]"', $added->body);

        $two = $this->post('owner', ['action' => 'add_exam', 'more' => [['title' => 'A']]] + $this->minimal());
        self::assertStringContainsString('name="more[1][title]"', $two->body);

        $removed = $this->post('owner', ['action' => 'remove_exam:0', 'more' => [['title' => 'A'], ['title' => 'B']]] + $this->minimal());
        self::assertStringContainsString('name="more[0][title]" value="B"', $removed->body);
        self::assertFalse($this->exists(self::PATH), 'nothing is created');
    }

    public function testSeveralExamsMakeOneReportWithAnAccessionEach(): void
    {
        $response = $this->post('owner', [
            'action' => 'create', 'title' => 'IRM genunchi drept', 'regions' => ['msk'],
            'more' => [['title' => 'IRM genunchi stâng', 'regions' => ['msk']], ['title' => 'IRM coloană lombară', 'regions' => ['spine']]],
        ] + $this->minimal());

        self::assertSame(302, $response->status);
        $page = $this->storage()->read(self::PATH);
        $fm = $page->frontmatter;
        self::assertSame('IRM genunchi drept + IRM genunchi stâng + IRM coloană lombară', $fm['exam_title']);
        self::assertSame(['msk', 'spine'], $fm['region'], 'the exams\' regions, once each');
        self::assertArrayNotHasKey('accession', $fm, 'numbers per exam, none for the page');
        self::assertSame([
            ['title' => 'IRM genunchi drept', 'region' => ['msk'], 'accession' => 'MV-MR-26-0001'],
            ['title' => 'IRM genunchi stâng', 'region' => ['msk'], 'accession' => 'MV-MR-26-0002'],
            ['title' => 'IRM coloană lombară', 'region' => ['spine'], 'accession' => 'MV-MR-26-0003'],
        ], $fm['exams']);
        self::assertSame(
            "# POPESCU Ana Maria\n\n## IRM genunchi drept\n\n### Descriere\n\n### Concluzii\n\n## IRM genunchi stâng\n\n### Descriere\n\n### Concluzii\n\n## IRM coloană lombară\n\n### Descriere\n\n### Concluzii\n",
            $page->body
        );
        self::assertSame([], \Reporion\Support\Exams::problems($fm, $page->body), 'whole from the start');

        // The next report does not reuse the 2nd or 3rd number (D20)
        $next = $this->post('owner', ['action' => 'create', 'name' => 'IONESCU Test', 'title' => 'IRM cerebral'] + $this->minimal());
        self::assertSame(302, $next->status);
        self::assertSame('MV-MR-26-0004', $this->storage()->read('reports:mri:mioveni:260926-ionescu-test')->frontmatter['accession']);
    }

    public function testEachExamNeedsATitle(): void
    {
        $response = $this->post('owner', ['action' => 'create', 'title' => 'IRM genunchi drept', 'more' => [['title' => '']]] + $this->minimal());

        self::assertSame(422, $response->status);
        self::assertStringContainsString('Each exam needs a title', $response->body);
        self::assertFalse($this->exists(self::PATH));
    }

    /** @return array<string, mixed> */
    private function minimal(): array
    {
        return ['name' => 'POPESCU Ana Maria', 'date' => '2026-09-26', 'modality' => 'MR', 'site' => 'mioveni', 'sex' => 'F', 'born' => '1980'];
    }

    /** @param array<string, mixed> $fields */
    private function post(string $user, array $fields): Response
    {
        return Kernel::boot($this->config)->handle(new Request('POST', '/new', cookies: ['reporion' => $this->cookie($user)], body: http_build_query(['guided' => '1'] + $fields)));
    }

    private function get(string $user, string $path): Response
    {
        return Kernel::boot($this->config)->handle(new Request('GET', $path, cookies: ['reporion' => $this->cookie($user)]));
    }

    private function cookie(string $user): string
    {
        return (new Session('test-secret', 'reporion', 3600, new FlatFileUserStore($this->dataRoot)))->issue($user);
    }

    private function exists(string $path): bool
    {
        return is_file($this->dataRoot . '/pages/' . str_replace(':', '/', $path) . '/meta.json');
    }

    private function storage(): FlatFile
    {
        return new FlatFile($this->dataRoot, new Sqlite((string) $this->config['paths']['index'], \dirname(__DIR__, 2) . '/migrations'));
    }
}
